// Code generated by generator.go; DO NOT EDIT.
//go:build cuda12
// +build cuda12

package gocu

/*
#include <cuda.h>
*/
import "C"

// Constants for ContextFlag.
const (
	CuCtxCoredumpEnable     ContextFlag = C.CU_CTX_COREDUMP_ENABLE // Trigger coredumps from exceptions in this context
	CuCtxFlagsMask          ContextFlag = C.CU_CTX_FLAGS_MASK
	CuCtxLmemResizeToMax    ContextFlag = C.CU_CTX_LMEM_RESIZE_TO_MAX  // Keep local memory allocation after launch
	CuCtxSchedAuto          ContextFlag = C.CU_CTX_SCHED_AUTO          // Automatic scheduling
	CuCtxSchedBlockingSync  ContextFlag = C.CU_CTX_SCHED_BLOCKING_SYNC // Set blocking synchronization as default scheduling
	CuCtxSchedMask          ContextFlag = C.CU_CTX_SCHED_MASK
	CuCtxSchedSpin          ContextFlag = C.CU_CTX_SCHED_SPIN           // Set spin as default scheduling
	CuCtxSchedYield         ContextFlag = C.CU_CTX_SCHED_YIELD          // Set yield as default scheduling
	CuCtxSyncMemops         ContextFlag = C.CU_CTX_SYNC_MEMOPS          // Ensure synchronous memory operations on this context will synchronize
	CuCtxUserCoredumpEnable ContextFlag = C.CU_CTX_USER_COREDUMP_ENABLE // Enable user pipe to trigger coredumps in this context
)

// ContextFlagMessages maps ContextFlag values to their string representations.
var ContextFlagMessages = map[ContextFlag]string{
	CuCtxCoredumpEnable:     "CuCtxCoredumpEnable",
	CuCtxFlagsMask:          "CuCtxFlagsMask",
	CuCtxLmemResizeToMax:    "CuCtxLmemResizeToMax",
	CuCtxSchedAuto:          "CuCtxSchedAuto",
	CuCtxSchedBlockingSync:  "CuCtxSchedBlockingSync",
	CuCtxSchedMask:          "CuCtxSchedMask",
	CuCtxSchedSpin:          "CuCtxSchedSpin",
	CuCtxSchedYield:         "CuCtxSchedYield",
	CuCtxSyncMemops:         "CuCtxSyncMemops",
	CuCtxUserCoredumpEnable: "CuCtxUserCoredumpEnable",
}
