// Code generated by generator.go; DO NOT EDIT.
//go:build !cuda11 || !cuda12 || !cuda13
// +build !cuda11 !cuda12 !cuda13

package gocu

/*
#include <cuda.h>
*/
import "C"

// Constants for ContextFlag.
const (
	CuCtxLmemResizeToMax   ContextFlag = C.CU_CTX_LMEM_RESIZE_TO_MAX  // Keep local memory allocation after launch
	CuCtxSchedAuto         ContextFlag = C.CU_CTX_SCHED_AUTO          // Automatic scheduling
	CuCtxSchedBlockingSync ContextFlag = C.CU_CTX_SCHED_BLOCKING_SYNC // Set blocking synchronization as default scheduling
	CuCtxSchedMask         ContextFlag = C.CU_CTX_SCHED_MASK
	CuCtxSchedSpin         ContextFlag = C.CU_CTX_SCHED_SPIN  // Set spin as default scheduling
	CuCtxSchedYield        ContextFlag = C.CU_CTX_SCHED_YIELD // Set yield as default scheduling
)

// ContextFlagMessages maps ContextFlag values to their string representations.
var ContextFlagMessages = map[ContextFlag]string{
	CuCtxLmemResizeToMax:   "CuCtxLmemResizeToMax",
	CuCtxSchedAuto:         "CuCtxSchedAuto",
	CuCtxSchedBlockingSync: "CuCtxSchedBlockingSync",
	CuCtxSchedMask:         "CuCtxSchedMask",
	CuCtxSchedSpin:         "CuCtxSchedSpin",
	CuCtxSchedYield:        "CuCtxSchedYield",
}
