// Code generated by generator.go; DO NOT EDIT.
//go:build !cuda11 || !cuda12 || !cuda13
// +build !cuda11 !cuda12 !cuda13

package gocu

/*
#include <cuda.h>
*/
import "C"

// Constants for JitOption.
const (
	CuJitCacheMode                     JitOption = C.CU_JIT_CACHE_MODE
	CuJitErrorLogBuffer                JitOption = C.CU_JIT_ERROR_LOG_BUFFER
	CuJitErrorLogBufferSizeBytes       JitOption = C.CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES
	CuJitFallbackStrategy              JitOption = C.CU_JIT_FALLBACK_STRATEGY
	CuJitFastCompile                   JitOption = C.CU_JIT_FAST_COMPILE
	CuJitFma                           JitOption = C.CU_JIT_FMA
	CuJitFtz                           JitOption = C.CU_JIT_FTZ
	CuJitGenerateDebugInfo             JitOption = C.CU_JIT_GENERATE_DEBUG_INFO
	CuJitGenerateLineInfo              JitOption = C.CU_JIT_GENERATE_LINE_INFO
	CuJitGlobalSymbolAddresses         JitOption = C.CU_JIT_GLOBAL_SYMBOL_ADDRESSES
	CuJitGlobalSymbolCount             JitOption = C.CU_JIT_GLOBAL_SYMBOL_COUNT
	CuJitGlobalSymbolNames             JitOption = C.CU_JIT_GLOBAL_SYMBOL_NAMES
	CuJitInfoLogBuffer                 JitOption = C.CU_JIT_INFO_LOG_BUFFER
	CuJitInfoLogBufferSizeBytes        JitOption = C.CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES
	CuJitLogVerbose                    JitOption = C.CU_JIT_LOG_VERBOSE
	CuJitLto                           JitOption = C.CU_JIT_LTO
	CuJitMaxRegisters                  JitOption = C.CU_JIT_MAX_REGISTERS
	CuJitNewSm3xOpt                    JitOption = C.CU_JIT_NEW_SM3X_OPT
	CuJitNumOptions                    JitOption = C.CU_JIT_NUM_OPTIONS
	CuJitOptimizationLevel             JitOption = C.CU_JIT_OPTIMIZATION_LEVEL
	CuJitOptimizeUnusedDeviceVariables JitOption = C.CU_JIT_OPTIMIZE_UNUSED_DEVICE_VARIABLES
	CuJitPrecDiv                       JitOption = C.CU_JIT_PREC_DIV
	CuJitPrecSqrt                      JitOption = C.CU_JIT_PREC_SQRT
	CuJitReferencedKernelCount         JitOption = C.CU_JIT_REFERENCED_KERNEL_COUNT
	CuJitReferencedKernelNames         JitOption = C.CU_JIT_REFERENCED_KERNEL_NAMES
	CuJitReferencedVariableCount       JitOption = C.CU_JIT_REFERENCED_VARIABLE_COUNT
	CuJitReferencedVariableNames       JitOption = C.CU_JIT_REFERENCED_VARIABLE_NAMES
	CuJitTarget                        JitOption = C.CU_JIT_TARGET
	CuJitTargetFromCucontext           JitOption = C.CU_JIT_TARGET_FROM_CUCONTEXT
	CuJitThreadsPerBlock               JitOption = C.CU_JIT_THREADS_PER_BLOCK
	CuJitWallTime                      JitOption = C.CU_JIT_WALL_TIME
)

// JitOptionMessages maps JitOption values to their string representations.
var JitOptionMessages = map[JitOption]string{
	CuJitCacheMode:                     "CuJitCacheMode",
	CuJitErrorLogBuffer:                "CuJitErrorLogBuffer",
	CuJitErrorLogBufferSizeBytes:       "CuJitErrorLogBufferSizeBytes",
	CuJitFallbackStrategy:              "CuJitFallbackStrategy",
	CuJitFastCompile:                   "CuJitFastCompile",
	CuJitFma:                           "CuJitFma",
	CuJitFtz:                           "CuJitFtz",
	CuJitGenerateDebugInfo:             "CuJitGenerateDebugInfo",
	CuJitGenerateLineInfo:              "CuJitGenerateLineInfo",
	CuJitGlobalSymbolAddresses:         "CuJitGlobalSymbolAddresses",
	CuJitGlobalSymbolCount:             "CuJitGlobalSymbolCount",
	CuJitGlobalSymbolNames:             "CuJitGlobalSymbolNames",
	CuJitInfoLogBuffer:                 "CuJitInfoLogBuffer",
	CuJitInfoLogBufferSizeBytes:        "CuJitInfoLogBufferSizeBytes",
	CuJitLogVerbose:                    "CuJitLogVerbose",
	CuJitLto:                           "CuJitLto",
	CuJitMaxRegisters:                  "CuJitMaxRegisters",
	CuJitNewSm3xOpt:                    "CuJitNewSm3xOpt",
	CuJitNumOptions:                    "CuJitNumOptions",
	CuJitOptimizationLevel:             "CuJitOptimizationLevel",
	CuJitOptimizeUnusedDeviceVariables: "CuJitOptimizeUnusedDeviceVariables",
	CuJitPrecDiv:                       "CuJitPrecDiv",
	CuJitPrecSqrt:                      "CuJitPrecSqrt",
	CuJitReferencedKernelCount:         "CuJitReferencedKernelCount",
	CuJitReferencedKernelNames:         "CuJitReferencedKernelNames",
	CuJitReferencedVariableCount:       "CuJitReferencedVariableCount",
	CuJitReferencedVariableNames:       "CuJitReferencedVariableNames",
	CuJitTarget:                        "CuJitTarget",
	CuJitTargetFromCucontext:           "CuJitTargetFromCucontext",
	CuJitThreadsPerBlock:               "CuJitThreadsPerBlock",
	CuJitWallTime:                      "CuJitWallTime",
}
