// Code generated by generator.go; DO NOT EDIT.
//go:build cuda13
// +build cuda13

package cudart

/*
#include <cuda_runtime.h>
*/
import "C"

// Constants for CudaError.
const (
	CudaErrorAddressOfConstant              CudaError = C.cudaErrorAddressOfConstant
	CudaErrorAlreadyAcquired                CudaError = C.cudaErrorAlreadyAcquired
	CudaErrorAlreadyMapped                  CudaError = C.cudaErrorAlreadyMapped
	CudaErrorArrayIsMapped                  CudaError = C.cudaErrorArrayIsMapped
	CudaErrorAssert                         CudaError = C.cudaErrorAssert
	CudaErrorCallRequiresNewerDriver        CudaError = C.cudaErrorCallRequiresNewerDriver
	CudaErrorCapturedEvent                  CudaError = C.cudaErrorCapturedEvent
	CudaErrorCdpNotSupported                CudaError = C.cudaErrorCdpNotSupported
	CudaErrorCdpVersionMismatch             CudaError = C.cudaErrorCdpVersionMismatch
	CudaErrorCompatNotSupportedOnDevice     CudaError = C.cudaErrorCompatNotSupportedOnDevice
	CudaErrorContained                      CudaError = C.cudaErrorContained
	CudaErrorContextIsDestroyed             CudaError = C.cudaErrorContextIsDestroyed
	CudaErrorCooperativeLaunchTooLarge      CudaError = C.cudaErrorCooperativeLaunchTooLarge
	CudaErrorCudartUnloading                CudaError = C.cudaErrorCudartUnloading
	CudaErrorDeviceAlreadyInUse             CudaError = C.cudaErrorDeviceAlreadyInUse
	CudaErrorDeviceNotLicensed              CudaError = C.cudaErrorDeviceNotLicensed
	CudaErrorDeviceUninitialized            CudaError = C.cudaErrorDeviceUninitialized
	CudaErrorDevicesUnavailable             CudaError = C.cudaErrorDevicesUnavailable
	CudaErrorDuplicateSurfaceName           CudaError = C.cudaErrorDuplicateSurfaceName
	CudaErrorDuplicateTextureName           CudaError = C.cudaErrorDuplicateTextureName
	CudaErrorDuplicateVariableName          CudaError = C.cudaErrorDuplicateVariableName
	CudaErrorEccuncorrectable               CudaError = C.cudaErrorECCUncorrectable
	CudaErrorExternalDevice                 CudaError = C.cudaErrorExternalDevice
	CudaErrorFileNotFound                   CudaError = C.cudaErrorFileNotFound
	CudaErrorFunctionNotLoaded              CudaError = C.cudaErrorFunctionNotLoaded
	CudaErrorGraphExecUpdateFailure         CudaError = C.cudaErrorGraphExecUpdateFailure
	CudaErrorHardwareStackError             CudaError = C.cudaErrorHardwareStackError
	CudaErrorHostMemoryAlreadyRegistered    CudaError = C.cudaErrorHostMemoryAlreadyRegistered
	CudaErrorHostMemoryNotRegistered        CudaError = C.cudaErrorHostMemoryNotRegistered
	CudaErrorIllegalAddress                 CudaError = C.cudaErrorIllegalAddress
	CudaErrorIllegalInstruction             CudaError = C.cudaErrorIllegalInstruction
	CudaErrorIllegalState                   CudaError = C.cudaErrorIllegalState
	CudaErrorIncompatibleDriverContext      CudaError = C.cudaErrorIncompatibleDriverContext
	CudaErrorInitializationError            CudaError = C.cudaErrorInitializationError
	CudaErrorInsufficientDriver             CudaError = C.cudaErrorInsufficientDriver
	CudaErrorInvalidAddressSpace            CudaError = C.cudaErrorInvalidAddressSpace
	CudaErrorInvalidChannelDescriptor       CudaError = C.cudaErrorInvalidChannelDescriptor
	CudaErrorInvalidClusterSize             CudaError = C.cudaErrorInvalidClusterSize
	CudaErrorInvalidConfiguration           CudaError = C.cudaErrorInvalidConfiguration
	CudaErrorInvalidDevice                  CudaError = C.cudaErrorInvalidDevice
	CudaErrorInvalidDeviceFunction          CudaError = C.cudaErrorInvalidDeviceFunction
	CudaErrorInvalidDevicePointer           CudaError = C.cudaErrorInvalidDevicePointer
	CudaErrorInvalidFilterSetting           CudaError = C.cudaErrorInvalidFilterSetting
	CudaErrorInvalidGraphicsContext         CudaError = C.cudaErrorInvalidGraphicsContext
	CudaErrorInvalidHostPointer             CudaError = C.cudaErrorInvalidHostPointer
	CudaErrorInvalidKernelImage             CudaError = C.cudaErrorInvalidKernelImage
	CudaErrorInvalidMemcpyDirection         CudaError = C.cudaErrorInvalidMemcpyDirection
	CudaErrorInvalidNormSetting             CudaError = C.cudaErrorInvalidNormSetting
	CudaErrorInvalidPc                      CudaError = C.cudaErrorInvalidPc
	CudaErrorInvalidPitchValue              CudaError = C.cudaErrorInvalidPitchValue
	CudaErrorInvalidPtx                     CudaError = C.cudaErrorInvalidPtx
	CudaErrorInvalidResourceConfiguration   CudaError = C.cudaErrorInvalidResourceConfiguration
	CudaErrorInvalidResourceHandle          CudaError = C.cudaErrorInvalidResourceHandle
	CudaErrorInvalidResourceType            CudaError = C.cudaErrorInvalidResourceType
	CudaErrorInvalidSource                  CudaError = C.cudaErrorInvalidSource
	CudaErrorInvalidSurface                 CudaError = C.cudaErrorInvalidSurface
	CudaErrorInvalidSymbol                  CudaError = C.cudaErrorInvalidSymbol
	CudaErrorInvalidTexture                 CudaError = C.cudaErrorInvalidTexture
	CudaErrorInvalidTextureBinding          CudaError = C.cudaErrorInvalidTextureBinding
	CudaErrorInvalidValue                   CudaError = C.cudaErrorInvalidValue
	CudaErrorJitCompilationDisabled         CudaError = C.cudaErrorJitCompilationDisabled
	CudaErrorJitCompilerNotFound            CudaError = C.cudaErrorJitCompilerNotFound
	CudaErrorLaunchFailure                  CudaError = C.cudaErrorLaunchFailure
	CudaErrorLaunchFileScopedSurf           CudaError = C.cudaErrorLaunchFileScopedSurf
	CudaErrorLaunchFileScopedTex            CudaError = C.cudaErrorLaunchFileScopedTex
	CudaErrorLaunchIncompatibleTexturing    CudaError = C.cudaErrorLaunchIncompatibleTexturing
	CudaErrorLaunchMaxDepthExceeded         CudaError = C.cudaErrorLaunchMaxDepthExceeded
	CudaErrorLaunchOutOfResources           CudaError = C.cudaErrorLaunchOutOfResources
	CudaErrorLaunchPendingCountExceeded     CudaError = C.cudaErrorLaunchPendingCountExceeded
	CudaErrorLaunchTimeout                  CudaError = C.cudaErrorLaunchTimeout
	CudaErrorLossyQuery                     CudaError = C.cudaErrorLossyQuery
	CudaErrorMapBufferObjectFailed          CudaError = C.cudaErrorMapBufferObjectFailed
	CudaErrorMemoryAllocation               CudaError = C.cudaErrorMemoryAllocation
	CudaErrorMemoryValueTooLarge            CudaError = C.cudaErrorMemoryValueTooLarge
	CudaErrorMisalignedAddress              CudaError = C.cudaErrorMisalignedAddress
	CudaErrorMissingConfiguration           CudaError = C.cudaErrorMissingConfiguration
	CudaErrorMixedDeviceExecution           CudaError = C.cudaErrorMixedDeviceExecution
	CudaErrorMpsClientTerminated            CudaError = C.cudaErrorMpsClientTerminated
	CudaErrorMpsConnectionFailed            CudaError = C.cudaErrorMpsConnectionFailed
	CudaErrorMpsMaxClientsReached           CudaError = C.cudaErrorMpsMaxClientsReached
	CudaErrorMpsMaxConnectionsReached       CudaError = C.cudaErrorMpsMaxConnectionsReached
	CudaErrorMpsRpcFailure                  CudaError = C.cudaErrorMpsRpcFailure
	CudaErrorMpsServerNotReady              CudaError = C.cudaErrorMpsServerNotReady
	CudaErrorNoDevice                       CudaError = C.cudaErrorNoDevice
	CudaErrorNoKernelImageForDevice         CudaError = C.cudaErrorNoKernelImageForDevice
	CudaErrorNotMapped                      CudaError = C.cudaErrorNotMapped
	CudaErrorNotMappedAsArray               CudaError = C.cudaErrorNotMappedAsArray
	CudaErrorNotMappedAsPointer             CudaError = C.cudaErrorNotMappedAsPointer
	CudaErrorNotPermitted                   CudaError = C.cudaErrorNotPermitted
	CudaErrorNotReady                       CudaError = C.cudaErrorNotReady
	CudaErrorNotSupported                   CudaError = C.cudaErrorNotSupported
	CudaErrorNotYetImplemented              CudaError = C.cudaErrorNotYetImplemented
	CudaErrorNvlinkUncorrectable            CudaError = C.cudaErrorNvlinkUncorrectable
	CudaErrorOperatingSystem                CudaError = C.cudaErrorOperatingSystem
	CudaErrorPeerAccessAlreadyEnabled       CudaError = C.cudaErrorPeerAccessAlreadyEnabled
	CudaErrorPeerAccessNotEnabled           CudaError = C.cudaErrorPeerAccessNotEnabled
	CudaErrorPeerAccessUnsupported          CudaError = C.cudaErrorPeerAccessUnsupported
	CudaErrorPriorLaunchFailure             CudaError = C.cudaErrorPriorLaunchFailure
	CudaErrorProfilerAlreadyStarted         CudaError = C.cudaErrorProfilerAlreadyStarted
	CudaErrorProfilerAlreadyStopped         CudaError = C.cudaErrorProfilerAlreadyStopped
	CudaErrorProfilerDisabled               CudaError = C.cudaErrorProfilerDisabled
	CudaErrorProfilerNotInitialized         CudaError = C.cudaErrorProfilerNotInitialized
	CudaErrorSetOnActiveProcess             CudaError = C.cudaErrorSetOnActiveProcess
	CudaErrorSharedObjectInitFailed         CudaError = C.cudaErrorSharedObjectInitFailed
	CudaErrorSharedObjectSymbolNotFound     CudaError = C.cudaErrorSharedObjectSymbolNotFound
	CudaErrorSoftwareValidityNotEstablished CudaError = C.cudaErrorSoftwareValidityNotEstablished
	CudaErrorStartupFailure                 CudaError = C.cudaErrorStartupFailure
	CudaErrorStreamCaptureImplicit          CudaError = C.cudaErrorStreamCaptureImplicit
	CudaErrorStreamCaptureInvalidated       CudaError = C.cudaErrorStreamCaptureInvalidated
	CudaErrorStreamCaptureIsolation         CudaError = C.cudaErrorStreamCaptureIsolation
	CudaErrorStreamCaptureMerge             CudaError = C.cudaErrorStreamCaptureMerge
	CudaErrorStreamCaptureUnjoined          CudaError = C.cudaErrorStreamCaptureUnjoined
	CudaErrorStreamCaptureUnmatched         CudaError = C.cudaErrorStreamCaptureUnmatched
	CudaErrorStreamCaptureUnsupported       CudaError = C.cudaErrorStreamCaptureUnsupported
	CudaErrorStreamCaptureWrongThread       CudaError = C.cudaErrorStreamCaptureWrongThread
	CudaErrorStubLibrary                    CudaError = C.cudaErrorStubLibrary
	CudaErrorSymbolNotFound                 CudaError = C.cudaErrorSymbolNotFound
	CudaErrorSyncDepthExceeded              CudaError = C.cudaErrorSyncDepthExceeded
	CudaErrorSynchronizationError           CudaError = C.cudaErrorSynchronizationError
	CudaErrorSystemDriverMismatch           CudaError = C.cudaErrorSystemDriverMismatch
	CudaErrorSystemNotReady                 CudaError = C.cudaErrorSystemNotReady
	CudaErrorTensorMemoryLeak               CudaError = C.cudaErrorTensorMemoryLeak
	CudaErrorTextureFetchFailed             CudaError = C.cudaErrorTextureFetchFailed
	CudaErrorTextureNotBound                CudaError = C.cudaErrorTextureNotBound
	CudaErrorTimeout                        CudaError = C.cudaErrorTimeout
	CudaErrorTooManyPeers                   CudaError = C.cudaErrorTooManyPeers
	CudaErrorUnknown                        CudaError = C.cudaErrorUnknown
	CudaErrorUnmapBufferObjectFailed        CudaError = C.cudaErrorUnmapBufferObjectFailed
	CudaErrorUnsupportedDevSideSync         CudaError = C.cudaErrorUnsupportedDevSideSync
	CudaErrorUnsupportedExecAffinity        CudaError = C.cudaErrorUnsupportedExecAffinity
	CudaErrorUnsupportedLimit               CudaError = C.cudaErrorUnsupportedLimit
	CudaErrorUnsupportedPtxVersion          CudaError = C.cudaErrorUnsupportedPtxVersion
	CudaSuccess                             CudaError = C.cudaSuccess
)

// ErrorMessages maps CudaError values to their string representations.
var ErrorMessages = map[CudaError]string{
	CudaErrorAddressOfConstant:              "CudaErrorAddressOfConstant",
	CudaErrorAlreadyAcquired:                "CudaErrorAlreadyAcquired",
	CudaErrorAlreadyMapped:                  "CudaErrorAlreadyMapped",
	CudaErrorArrayIsMapped:                  "CudaErrorArrayIsMapped",
	CudaErrorAssert:                         "CudaErrorAssert",
	CudaErrorCallRequiresNewerDriver:        "CudaErrorCallRequiresNewerDriver",
	CudaErrorCapturedEvent:                  "CudaErrorCapturedEvent",
	CudaErrorCdpNotSupported:                "CudaErrorCdpNotSupported",
	CudaErrorCdpVersionMismatch:             "CudaErrorCdpVersionMismatch",
	CudaErrorCompatNotSupportedOnDevice:     "CudaErrorCompatNotSupportedOnDevice",
	CudaErrorContained:                      "CudaErrorContained",
	CudaErrorContextIsDestroyed:             "CudaErrorContextIsDestroyed",
	CudaErrorCooperativeLaunchTooLarge:      "CudaErrorCooperativeLaunchTooLarge",
	CudaErrorCudartUnloading:                "CudaErrorCudartUnloading",
	CudaErrorDeviceAlreadyInUse:             "CudaErrorDeviceAlreadyInUse",
	CudaErrorDeviceNotLicensed:              "CudaErrorDeviceNotLicensed",
	CudaErrorDeviceUninitialized:            "CudaErrorDeviceUninitialized",
	CudaErrorDevicesUnavailable:             "CudaErrorDevicesUnavailable",
	CudaErrorDuplicateSurfaceName:           "CudaErrorDuplicateSurfaceName",
	CudaErrorDuplicateTextureName:           "CudaErrorDuplicateTextureName",
	CudaErrorDuplicateVariableName:          "CudaErrorDuplicateVariableName",
	CudaErrorEccuncorrectable:               "CudaErrorEccuncorrectable",
	CudaErrorExternalDevice:                 "CudaErrorExternalDevice",
	CudaErrorFileNotFound:                   "CudaErrorFileNotFound",
	CudaErrorFunctionNotLoaded:              "CudaErrorFunctionNotLoaded",
	CudaErrorGraphExecUpdateFailure:         "CudaErrorGraphExecUpdateFailure",
	CudaErrorHardwareStackError:             "CudaErrorHardwareStackError",
	CudaErrorHostMemoryAlreadyRegistered:    "CudaErrorHostMemoryAlreadyRegistered",
	CudaErrorHostMemoryNotRegistered:        "CudaErrorHostMemoryNotRegistered",
	CudaErrorIllegalAddress:                 "CudaErrorIllegalAddress",
	CudaErrorIllegalInstruction:             "CudaErrorIllegalInstruction",
	CudaErrorIllegalState:                   "CudaErrorIllegalState",
	CudaErrorIncompatibleDriverContext:      "CudaErrorIncompatibleDriverContext",
	CudaErrorInitializationError:            "CudaErrorInitializationError",
	CudaErrorInsufficientDriver:             "CudaErrorInsufficientDriver",
	CudaErrorInvalidAddressSpace:            "CudaErrorInvalidAddressSpace",
	CudaErrorInvalidChannelDescriptor:       "CudaErrorInvalidChannelDescriptor",
	CudaErrorInvalidClusterSize:             "CudaErrorInvalidClusterSize",
	CudaErrorInvalidConfiguration:           "CudaErrorInvalidConfiguration",
	CudaErrorInvalidDevice:                  "CudaErrorInvalidDevice",
	CudaErrorInvalidDeviceFunction:          "CudaErrorInvalidDeviceFunction",
	CudaErrorInvalidDevicePointer:           "CudaErrorInvalidDevicePointer",
	CudaErrorInvalidFilterSetting:           "CudaErrorInvalidFilterSetting",
	CudaErrorInvalidGraphicsContext:         "CudaErrorInvalidGraphicsContext",
	CudaErrorInvalidHostPointer:             "CudaErrorInvalidHostPointer",
	CudaErrorInvalidKernelImage:             "CudaErrorInvalidKernelImage",
	CudaErrorInvalidMemcpyDirection:         "CudaErrorInvalidMemcpyDirection",
	CudaErrorInvalidNormSetting:             "CudaErrorInvalidNormSetting",
	CudaErrorInvalidPc:                      "CudaErrorInvalidPc",
	CudaErrorInvalidPitchValue:              "CudaErrorInvalidPitchValue",
	CudaErrorInvalidPtx:                     "CudaErrorInvalidPtx",
	CudaErrorInvalidResourceConfiguration:   "CudaErrorInvalidResourceConfiguration",
	CudaErrorInvalidResourceHandle:          "CudaErrorInvalidResourceHandle",
	CudaErrorInvalidResourceType:            "CudaErrorInvalidResourceType",
	CudaErrorInvalidSource:                  "CudaErrorInvalidSource",
	CudaErrorInvalidSurface:                 "CudaErrorInvalidSurface",
	CudaErrorInvalidSymbol:                  "CudaErrorInvalidSymbol",
	CudaErrorInvalidTexture:                 "CudaErrorInvalidTexture",
	CudaErrorInvalidTextureBinding:          "CudaErrorInvalidTextureBinding",
	CudaErrorInvalidValue:                   "CudaErrorInvalidValue",
	CudaErrorJitCompilationDisabled:         "CudaErrorJitCompilationDisabled",
	CudaErrorJitCompilerNotFound:            "CudaErrorJitCompilerNotFound",
	CudaErrorLaunchFailure:                  "CudaErrorLaunchFailure",
	CudaErrorLaunchFileScopedSurf:           "CudaErrorLaunchFileScopedSurf",
	CudaErrorLaunchFileScopedTex:            "CudaErrorLaunchFileScopedTex",
	CudaErrorLaunchIncompatibleTexturing:    "CudaErrorLaunchIncompatibleTexturing",
	CudaErrorLaunchMaxDepthExceeded:         "CudaErrorLaunchMaxDepthExceeded",
	CudaErrorLaunchOutOfResources:           "CudaErrorLaunchOutOfResources",
	CudaErrorLaunchPendingCountExceeded:     "CudaErrorLaunchPendingCountExceeded",
	CudaErrorLaunchTimeout:                  "CudaErrorLaunchTimeout",
	CudaErrorLossyQuery:                     "CudaErrorLossyQuery",
	CudaErrorMapBufferObjectFailed:          "CudaErrorMapBufferObjectFailed",
	CudaErrorMemoryAllocation:               "CudaErrorMemoryAllocation",
	CudaErrorMemoryValueTooLarge:            "CudaErrorMemoryValueTooLarge",
	CudaErrorMisalignedAddress:              "CudaErrorMisalignedAddress",
	CudaErrorMissingConfiguration:           "CudaErrorMissingConfiguration",
	CudaErrorMixedDeviceExecution:           "CudaErrorMixedDeviceExecution",
	CudaErrorMpsClientTerminated:            "CudaErrorMpsClientTerminated",
	CudaErrorMpsConnectionFailed:            "CudaErrorMpsConnectionFailed",
	CudaErrorMpsMaxClientsReached:           "CudaErrorMpsMaxClientsReached",
	CudaErrorMpsMaxConnectionsReached:       "CudaErrorMpsMaxConnectionsReached",
	CudaErrorMpsRpcFailure:                  "CudaErrorMpsRpcFailure",
	CudaErrorMpsServerNotReady:              "CudaErrorMpsServerNotReady",
	CudaErrorNoDevice:                       "CudaErrorNoDevice",
	CudaErrorNoKernelImageForDevice:         "CudaErrorNoKernelImageForDevice",
	CudaErrorNotMapped:                      "CudaErrorNotMapped",
	CudaErrorNotMappedAsArray:               "CudaErrorNotMappedAsArray",
	CudaErrorNotMappedAsPointer:             "CudaErrorNotMappedAsPointer",
	CudaErrorNotPermitted:                   "CudaErrorNotPermitted",
	CudaErrorNotReady:                       "CudaErrorNotReady",
	CudaErrorNotSupported:                   "CudaErrorNotSupported",
	CudaErrorNotYetImplemented:              "CudaErrorNotYetImplemented",
	CudaErrorNvlinkUncorrectable:            "CudaErrorNvlinkUncorrectable",
	CudaErrorOperatingSystem:                "CudaErrorOperatingSystem",
	CudaErrorPeerAccessAlreadyEnabled:       "CudaErrorPeerAccessAlreadyEnabled",
	CudaErrorPeerAccessNotEnabled:           "CudaErrorPeerAccessNotEnabled",
	CudaErrorPeerAccessUnsupported:          "CudaErrorPeerAccessUnsupported",
	CudaErrorPriorLaunchFailure:             "CudaErrorPriorLaunchFailure",
	CudaErrorProfilerAlreadyStarted:         "CudaErrorProfilerAlreadyStarted",
	CudaErrorProfilerAlreadyStopped:         "CudaErrorProfilerAlreadyStopped",
	CudaErrorProfilerDisabled:               "CudaErrorProfilerDisabled",
	CudaErrorProfilerNotInitialized:         "CudaErrorProfilerNotInitialized",
	CudaErrorSetOnActiveProcess:             "CudaErrorSetOnActiveProcess",
	CudaErrorSharedObjectInitFailed:         "CudaErrorSharedObjectInitFailed",
	CudaErrorSharedObjectSymbolNotFound:     "CudaErrorSharedObjectSymbolNotFound",
	CudaErrorSoftwareValidityNotEstablished: "CudaErrorSoftwareValidityNotEstablished",
	CudaErrorStartupFailure:                 "CudaErrorStartupFailure",
	CudaErrorStreamCaptureImplicit:          "CudaErrorStreamCaptureImplicit",
	CudaErrorStreamCaptureInvalidated:       "CudaErrorStreamCaptureInvalidated",
	CudaErrorStreamCaptureIsolation:         "CudaErrorStreamCaptureIsolation",
	CudaErrorStreamCaptureMerge:             "CudaErrorStreamCaptureMerge",
	CudaErrorStreamCaptureUnjoined:          "CudaErrorStreamCaptureUnjoined",
	CudaErrorStreamCaptureUnmatched:         "CudaErrorStreamCaptureUnmatched",
	CudaErrorStreamCaptureUnsupported:       "CudaErrorStreamCaptureUnsupported",
	CudaErrorStreamCaptureWrongThread:       "CudaErrorStreamCaptureWrongThread",
	CudaErrorStubLibrary:                    "CudaErrorStubLibrary",
	CudaErrorSymbolNotFound:                 "CudaErrorSymbolNotFound",
	CudaErrorSyncDepthExceeded:              "CudaErrorSyncDepthExceeded",
	CudaErrorSynchronizationError:           "CudaErrorSynchronizationError",
	CudaErrorSystemDriverMismatch:           "CudaErrorSystemDriverMismatch",
	CudaErrorSystemNotReady:                 "CudaErrorSystemNotReady",
	CudaErrorTensorMemoryLeak:               "CudaErrorTensorMemoryLeak",
	CudaErrorTextureFetchFailed:             "CudaErrorTextureFetchFailed",
	CudaErrorTextureNotBound:                "CudaErrorTextureNotBound",
	CudaErrorTimeout:                        "CudaErrorTimeout",
	CudaErrorTooManyPeers:                   "CudaErrorTooManyPeers",
	CudaErrorUnknown:                        "CudaErrorUnknown",
	CudaErrorUnmapBufferObjectFailed:        "CudaErrorUnmapBufferObjectFailed",
	CudaErrorUnsupportedDevSideSync:         "CudaErrorUnsupportedDevSideSync",
	CudaErrorUnsupportedExecAffinity:        "CudaErrorUnsupportedExecAffinity",
	CudaErrorUnsupportedLimit:               "CudaErrorUnsupportedLimit",
	CudaErrorUnsupportedPtxVersion:          "CudaErrorUnsupportedPtxVersion",
	CudaSuccess:                             "CudaSuccess",
}
