// Code generated by generator.go; DO NOT EDIT.
//go:build cuda13
// +build cuda13

package cudart

/*
#include <cuda_runtime.h>
*/
import "C"

// Constants for CudaDeviceAttr.
const (
	CudaDevAttrAsyncEngineCount                       CudaDeviceAttr = C.cudaDevAttrAsyncEngineCount
	CudaDevAttrCanFlushRemoteWrites                   CudaDeviceAttr = C.cudaDevAttrCanFlushRemoteWrites
	CudaDevAttrCanMapHostMemory                       CudaDeviceAttr = C.cudaDevAttrCanMapHostMemory
	CudaDevAttrCanUseHostPointerForRegisteredMem      CudaDeviceAttr = C.cudaDevAttrCanUseHostPointerForRegisteredMem
	CudaDevAttrClockRate                              CudaDeviceAttr = C.cudaDevAttrClockRate
	CudaDevAttrClusterLaunch                          CudaDeviceAttr = C.cudaDevAttrClusterLaunch
	CudaDevAttrComputeCapabilityMajor                 CudaDeviceAttr = C.cudaDevAttrComputeCapabilityMajor
	CudaDevAttrComputeCapabilityMinor                 CudaDeviceAttr = C.cudaDevAttrComputeCapabilityMinor
	CudaDevAttrComputeMode                            CudaDeviceAttr = C.cudaDevAttrComputeMode
	CudaDevAttrComputePreemptionSupported             CudaDeviceAttr = C.cudaDevAttrComputePreemptionSupported
	CudaDevAttrConcurrentKernels                      CudaDeviceAttr = C.cudaDevAttrConcurrentKernels
	CudaDevAttrConcurrentManagedAccess                CudaDeviceAttr = C.cudaDevAttrConcurrentManagedAccess
	CudaDevAttrCooperativeLaunch                      CudaDeviceAttr = C.cudaDevAttrCooperativeLaunch
	CudaDevAttrD3D12CigSupported                      CudaDeviceAttr = C.cudaDevAttrD3D12CigSupported
	CudaDevAttrDeferredMappingCudaArraySupported      CudaDeviceAttr = C.cudaDevAttrDeferredMappingCudaArraySupported
	CudaDevAttrDirectManagedMemAccessFromHost         CudaDeviceAttr = C.cudaDevAttrDirectManagedMemAccessFromHost
	CudaDevAttrEccEnabled                             CudaDeviceAttr = C.cudaDevAttrEccEnabled
	CudaDevAttrGpudirectRdmaflushWritesOptions        CudaDeviceAttr = C.cudaDevAttrGPUDirectRDMAFlushWritesOptions
	CudaDevAttrGpudirectRdmasupported                 CudaDeviceAttr = C.cudaDevAttrGPUDirectRDMASupported
	CudaDevAttrGpudirectRdmawritesOrdering            CudaDeviceAttr = C.cudaDevAttrGPUDirectRDMAWritesOrdering
	CudaDevAttrGlobalL1CacheSupported                 CudaDeviceAttr = C.cudaDevAttrGlobalL1CacheSupported
	CudaDevAttrGlobalMemoryBusWidth                   CudaDeviceAttr = C.cudaDevAttrGlobalMemoryBusWidth
	CudaDevAttrGpuOverlap                             CudaDeviceAttr = C.cudaDevAttrGpuOverlap
	CudaDevAttrGpuPciDeviceId                         CudaDeviceAttr = C.cudaDevAttrGpuPciDeviceId
	CudaDevAttrGpuPciSubsystemId                      CudaDeviceAttr = C.cudaDevAttrGpuPciSubsystemId
	CudaDevAttrHostMemoryPoolsSupported               CudaDeviceAttr = C.cudaDevAttrHostMemoryPoolsSupported
	CudaDevAttrHostNativeAtomicSupported              CudaDeviceAttr = C.cudaDevAttrHostNativeAtomicSupported
	CudaDevAttrHostNumaId                             CudaDeviceAttr = C.cudaDevAttrHostNumaId
	CudaDevAttrHostNumaMemoryPoolsSupported           CudaDeviceAttr = C.cudaDevAttrHostNumaMemoryPoolsSupported
	CudaDevAttrHostNumaMultinodeIpcSupported          CudaDeviceAttr = C.cudaDevAttrHostNumaMultinodeIpcSupported
	CudaDevAttrHostRegisterReadOnlySupported          CudaDeviceAttr = C.cudaDevAttrHostRegisterReadOnlySupported
	CudaDevAttrHostRegisterSupported                  CudaDeviceAttr = C.cudaDevAttrHostRegisterSupported
	CudaDevAttrIntegrated                             CudaDeviceAttr = C.cudaDevAttrIntegrated
	CudaDevAttrIpcEventSupport                        CudaDeviceAttr = C.cudaDevAttrIpcEventSupport
	CudaDevAttrIsMultiGpuBoard                        CudaDeviceAttr = C.cudaDevAttrIsMultiGpuBoard
	CudaDevAttrKernelExecTimeout                      CudaDeviceAttr = C.cudaDevAttrKernelExecTimeout
	CudaDevAttrL2CacheSize                            CudaDeviceAttr = C.cudaDevAttrL2CacheSize
	CudaDevAttrLocalL1CacheSupported                  CudaDeviceAttr = C.cudaDevAttrLocalL1CacheSupported
	CudaDevAttrManagedMemory                          CudaDeviceAttr = C.cudaDevAttrManagedMemory
	CudaDevAttrMaxAccessPolicyWindowSize              CudaDeviceAttr = C.cudaDevAttrMaxAccessPolicyWindowSize
	CudaDevAttrMaxBlockDimX                           CudaDeviceAttr = C.cudaDevAttrMaxBlockDimX
	CudaDevAttrMaxBlockDimY                           CudaDeviceAttr = C.cudaDevAttrMaxBlockDimY
	CudaDevAttrMaxBlockDimZ                           CudaDeviceAttr = C.cudaDevAttrMaxBlockDimZ
	CudaDevAttrMaxBlocksPerMultiprocessor             CudaDeviceAttr = C.cudaDevAttrMaxBlocksPerMultiprocessor
	CudaDevAttrMaxGridDimX                            CudaDeviceAttr = C.cudaDevAttrMaxGridDimX
	CudaDevAttrMaxGridDimY                            CudaDeviceAttr = C.cudaDevAttrMaxGridDimY
	CudaDevAttrMaxGridDimZ                            CudaDeviceAttr = C.cudaDevAttrMaxGridDimZ
	CudaDevAttrMaxPersistingL2CacheSize               CudaDeviceAttr = C.cudaDevAttrMaxPersistingL2CacheSize
	CudaDevAttrMaxPitch                               CudaDeviceAttr = C.cudaDevAttrMaxPitch
	CudaDevAttrMaxRegistersPerBlock                   CudaDeviceAttr = C.cudaDevAttrMaxRegistersPerBlock
	CudaDevAttrMaxRegistersPerMultiprocessor          CudaDeviceAttr = C.cudaDevAttrMaxRegistersPerMultiprocessor
	CudaDevAttrMaxSharedMemoryPerBlock                CudaDeviceAttr = C.cudaDevAttrMaxSharedMemoryPerBlock
	CudaDevAttrMaxSharedMemoryPerBlockOptin           CudaDeviceAttr = C.cudaDevAttrMaxSharedMemoryPerBlockOptin
	CudaDevAttrMaxSharedMemoryPerMultiprocessor       CudaDeviceAttr = C.cudaDevAttrMaxSharedMemoryPerMultiprocessor
	CudaDevAttrMaxSurface1DlayeredLayers              CudaDeviceAttr = C.cudaDevAttrMaxSurface1DLayeredLayers
	CudaDevAttrMaxSurface1DlayeredWidth               CudaDeviceAttr = C.cudaDevAttrMaxSurface1DLayeredWidth
	CudaDevAttrMaxSurface1Dwidth                      CudaDeviceAttr = C.cudaDevAttrMaxSurface1DWidth
	CudaDevAttrMaxSurface2Dheight                     CudaDeviceAttr = C.cudaDevAttrMaxSurface2DHeight
	CudaDevAttrMaxSurface2DlayeredHeight              CudaDeviceAttr = C.cudaDevAttrMaxSurface2DLayeredHeight
	CudaDevAttrMaxSurface2DlayeredLayers              CudaDeviceAttr = C.cudaDevAttrMaxSurface2DLayeredLayers
	CudaDevAttrMaxSurface2DlayeredWidth               CudaDeviceAttr = C.cudaDevAttrMaxSurface2DLayeredWidth
	CudaDevAttrMaxSurface2Dwidth                      CudaDeviceAttr = C.cudaDevAttrMaxSurface2DWidth
	CudaDevAttrMaxSurface3Ddepth                      CudaDeviceAttr = C.cudaDevAttrMaxSurface3DDepth
	CudaDevAttrMaxSurface3Dheight                     CudaDeviceAttr = C.cudaDevAttrMaxSurface3DHeight
	CudaDevAttrMaxSurface3Dwidth                      CudaDeviceAttr = C.cudaDevAttrMaxSurface3DWidth
	CudaDevAttrMaxSurfaceCubemapLayeredLayers         CudaDeviceAttr = C.cudaDevAttrMaxSurfaceCubemapLayeredLayers
	CudaDevAttrMaxSurfaceCubemapLayeredWidth          CudaDeviceAttr = C.cudaDevAttrMaxSurfaceCubemapLayeredWidth
	CudaDevAttrMaxSurfaceCubemapWidth                 CudaDeviceAttr = C.cudaDevAttrMaxSurfaceCubemapWidth
	CudaDevAttrMaxTexture1DlayeredLayers              CudaDeviceAttr = C.cudaDevAttrMaxTexture1DLayeredLayers
	CudaDevAttrMaxTexture1DlayeredWidth               CudaDeviceAttr = C.cudaDevAttrMaxTexture1DLayeredWidth
	CudaDevAttrMaxTexture1DlinearWidth                CudaDeviceAttr = C.cudaDevAttrMaxTexture1DLinearWidth
	CudaDevAttrMaxTexture1DmipmappedWidth             CudaDeviceAttr = C.cudaDevAttrMaxTexture1DMipmappedWidth
	CudaDevAttrMaxTexture1Dwidth                      CudaDeviceAttr = C.cudaDevAttrMaxTexture1DWidth
	CudaDevAttrMaxTexture2DgatherHeight               CudaDeviceAttr = C.cudaDevAttrMaxTexture2DGatherHeight
	CudaDevAttrMaxTexture2DgatherWidth                CudaDeviceAttr = C.cudaDevAttrMaxTexture2DGatherWidth
	CudaDevAttrMaxTexture2Dheight                     CudaDeviceAttr = C.cudaDevAttrMaxTexture2DHeight
	CudaDevAttrMaxTexture2DlayeredHeight              CudaDeviceAttr = C.cudaDevAttrMaxTexture2DLayeredHeight
	CudaDevAttrMaxTexture2DlayeredLayers              CudaDeviceAttr = C.cudaDevAttrMaxTexture2DLayeredLayers
	CudaDevAttrMaxTexture2DlayeredWidth               CudaDeviceAttr = C.cudaDevAttrMaxTexture2DLayeredWidth
	CudaDevAttrMaxTexture2DlinearHeight               CudaDeviceAttr = C.cudaDevAttrMaxTexture2DLinearHeight
	CudaDevAttrMaxTexture2DlinearPitch                CudaDeviceAttr = C.cudaDevAttrMaxTexture2DLinearPitch
	CudaDevAttrMaxTexture2DlinearWidth                CudaDeviceAttr = C.cudaDevAttrMaxTexture2DLinearWidth
	CudaDevAttrMaxTexture2DmipmappedHeight            CudaDeviceAttr = C.cudaDevAttrMaxTexture2DMipmappedHeight
	CudaDevAttrMaxTexture2DmipmappedWidth             CudaDeviceAttr = C.cudaDevAttrMaxTexture2DMipmappedWidth
	CudaDevAttrMaxTexture2Dwidth                      CudaDeviceAttr = C.cudaDevAttrMaxTexture2DWidth
	CudaDevAttrMaxTexture3Ddepth                      CudaDeviceAttr = C.cudaDevAttrMaxTexture3DDepth
	CudaDevAttrMaxTexture3DdepthAlt                   CudaDeviceAttr = C.cudaDevAttrMaxTexture3DDepthAlt
	CudaDevAttrMaxTexture3Dheight                     CudaDeviceAttr = C.cudaDevAttrMaxTexture3DHeight
	CudaDevAttrMaxTexture3DheightAlt                  CudaDeviceAttr = C.cudaDevAttrMaxTexture3DHeightAlt
	CudaDevAttrMaxTexture3Dwidth                      CudaDeviceAttr = C.cudaDevAttrMaxTexture3DWidth
	CudaDevAttrMaxTexture3DwidthAlt                   CudaDeviceAttr = C.cudaDevAttrMaxTexture3DWidthAlt
	CudaDevAttrMaxTextureCubemapLayeredLayers         CudaDeviceAttr = C.cudaDevAttrMaxTextureCubemapLayeredLayers
	CudaDevAttrMaxTextureCubemapLayeredWidth          CudaDeviceAttr = C.cudaDevAttrMaxTextureCubemapLayeredWidth
	CudaDevAttrMaxTextureCubemapWidth                 CudaDeviceAttr = C.cudaDevAttrMaxTextureCubemapWidth
	CudaDevAttrMaxThreadsPerBlock                     CudaDeviceAttr = C.cudaDevAttrMaxThreadsPerBlock
	CudaDevAttrMaxThreadsPerMultiProcessor            CudaDeviceAttr = C.cudaDevAttrMaxThreadsPerMultiProcessor
	CudaDevAttrMemSyncDomainCount                     CudaDeviceAttr = C.cudaDevAttrMemSyncDomainCount
	CudaDevAttrMemoryClockRate                        CudaDeviceAttr = C.cudaDevAttrMemoryClockRate
	CudaDevAttrMemoryPoolSupportedHandleTypes         CudaDeviceAttr = C.cudaDevAttrMemoryPoolSupportedHandleTypes
	CudaDevAttrMemoryPoolsSupported                   CudaDeviceAttr = C.cudaDevAttrMemoryPoolsSupported
	CudaDevAttrMpsEnabled                             CudaDeviceAttr = C.cudaDevAttrMpsEnabled
	CudaDevAttrMultiGpuBoardGroupId                   CudaDeviceAttr = C.cudaDevAttrMultiGpuBoardGroupID
	CudaDevAttrMultiProcessorCount                    CudaDeviceAttr = C.cudaDevAttrMultiProcessorCount
	CudaDevAttrNumaConfig                             CudaDeviceAttr = C.cudaDevAttrNumaConfig
	CudaDevAttrNumaId                                 CudaDeviceAttr = C.cudaDevAttrNumaId
	CudaDevAttrOnlyPartialHostNativeAtomicSupported   CudaDeviceAttr = C.cudaDevAttrOnlyPartialHostNativeAtomicSupported
	CudaDevAttrPageableMemoryAccess                   CudaDeviceAttr = C.cudaDevAttrPageableMemoryAccess
	CudaDevAttrPageableMemoryAccessUsesHostPageTables CudaDeviceAttr = C.cudaDevAttrPageableMemoryAccessUsesHostPageTables
	CudaDevAttrPciBusId                               CudaDeviceAttr = C.cudaDevAttrPciBusId
	CudaDevAttrPciDeviceId                            CudaDeviceAttr = C.cudaDevAttrPciDeviceId
	CudaDevAttrPciDomainId                            CudaDeviceAttr = C.cudaDevAttrPciDomainId
	CudaDevAttrReserved122                            CudaDeviceAttr = C.cudaDevAttrReserved122
	CudaDevAttrReserved123                            CudaDeviceAttr = C.cudaDevAttrReserved123
	CudaDevAttrReserved124                            CudaDeviceAttr = C.cudaDevAttrReserved124
	CudaDevAttrReserved127                            CudaDeviceAttr = C.cudaDevAttrReserved127
	CudaDevAttrReserved128                            CudaDeviceAttr = C.cudaDevAttrReserved128
	CudaDevAttrReserved129                            CudaDeviceAttr = C.cudaDevAttrReserved129
	CudaDevAttrReserved132                            CudaDeviceAttr = C.cudaDevAttrReserved132
	CudaDevAttrReserved141                            CudaDeviceAttr = C.cudaDevAttrReserved141
	CudaDevAttrReserved145                            CudaDeviceAttr = C.cudaDevAttrReserved145
	CudaDevAttrReserved92                             CudaDeviceAttr = C.cudaDevAttrReserved92
	CudaDevAttrReserved93                             CudaDeviceAttr = C.cudaDevAttrReserved93
	CudaDevAttrReserved94                             CudaDeviceAttr = C.cudaDevAttrReserved94
	CudaDevAttrReserved96                             CudaDeviceAttr = C.cudaDevAttrReserved96
	CudaDevAttrReservedSharedMemoryPerBlock           CudaDeviceAttr = C.cudaDevAttrReservedSharedMemoryPerBlock
	CudaDevAttrSingleToDoublePrecisionPerfRatio       CudaDeviceAttr = C.cudaDevAttrSingleToDoublePrecisionPerfRatio
	CudaDevAttrSparseCudaArraySupported               CudaDeviceAttr = C.cudaDevAttrSparseCudaArraySupported
	CudaDevAttrStreamPrioritiesSupported              CudaDeviceAttr = C.cudaDevAttrStreamPrioritiesSupported
	CudaDevAttrSurfaceAlignment                       CudaDeviceAttr = C.cudaDevAttrSurfaceAlignment
	CudaDevAttrTccDriver                              CudaDeviceAttr = C.cudaDevAttrTccDriver
	CudaDevAttrTextureAlignment                       CudaDeviceAttr = C.cudaDevAttrTextureAlignment
	CudaDevAttrTexturePitchAlignment                  CudaDeviceAttr = C.cudaDevAttrTexturePitchAlignment
	CudaDevAttrTimelineSemaphoreInteropSupported      CudaDeviceAttr = C.cudaDevAttrTimelineSemaphoreInteropSupported
	CudaDevAttrTotalConstantMemory                    CudaDeviceAttr = C.cudaDevAttrTotalConstantMemory
	CudaDevAttrUnifiedAddressing                      CudaDeviceAttr = C.cudaDevAttrUnifiedAddressing
	CudaDevAttrVulkanCigSupported                     CudaDeviceAttr = C.cudaDevAttrVulkanCigSupported
	CudaDevAttrWarpSize                               CudaDeviceAttr = C.cudaDevAttrWarpSize
)

// CudaDeviceAttrMessages maps CudaDeviceAttr values to their string representations.
var CudaDeviceAttrMessages = map[CudaDeviceAttr]string{
	CudaDevAttrAsyncEngineCount:                       "CudaDevAttrAsyncEngineCount",
	CudaDevAttrCanFlushRemoteWrites:                   "CudaDevAttrCanFlushRemoteWrites",
	CudaDevAttrCanMapHostMemory:                       "CudaDevAttrCanMapHostMemory",
	CudaDevAttrCanUseHostPointerForRegisteredMem:      "CudaDevAttrCanUseHostPointerForRegisteredMem",
	CudaDevAttrClockRate:                              "CudaDevAttrClockRate",
	CudaDevAttrClusterLaunch:                          "CudaDevAttrClusterLaunch",
	CudaDevAttrComputeCapabilityMajor:                 "CudaDevAttrComputeCapabilityMajor",
	CudaDevAttrComputeCapabilityMinor:                 "CudaDevAttrComputeCapabilityMinor",
	CudaDevAttrComputeMode:                            "CudaDevAttrComputeMode",
	CudaDevAttrComputePreemptionSupported:             "CudaDevAttrComputePreemptionSupported",
	CudaDevAttrConcurrentKernels:                      "CudaDevAttrConcurrentKernels",
	CudaDevAttrConcurrentManagedAccess:                "CudaDevAttrConcurrentManagedAccess",
	CudaDevAttrCooperativeLaunch:                      "CudaDevAttrCooperativeLaunch",
	CudaDevAttrD3D12CigSupported:                      "CudaDevAttrD3D12CigSupported",
	CudaDevAttrDeferredMappingCudaArraySupported:      "CudaDevAttrDeferredMappingCudaArraySupported",
	CudaDevAttrDirectManagedMemAccessFromHost:         "CudaDevAttrDirectManagedMemAccessFromHost",
	CudaDevAttrEccEnabled:                             "CudaDevAttrEccEnabled",
	CudaDevAttrGpudirectRdmaflushWritesOptions:        "CudaDevAttrGpudirectRdmaflushWritesOptions",
	CudaDevAttrGpudirectRdmasupported:                 "CudaDevAttrGpudirectRdmasupported",
	CudaDevAttrGpudirectRdmawritesOrdering:            "CudaDevAttrGpudirectRdmawritesOrdering",
	CudaDevAttrGlobalL1CacheSupported:                 "CudaDevAttrGlobalL1CacheSupported",
	CudaDevAttrGlobalMemoryBusWidth:                   "CudaDevAttrGlobalMemoryBusWidth",
	CudaDevAttrGpuOverlap:                             "CudaDevAttrGpuOverlap",
	CudaDevAttrGpuPciDeviceId:                         "CudaDevAttrGpuPciDeviceId",
	CudaDevAttrGpuPciSubsystemId:                      "CudaDevAttrGpuPciSubsystemId",
	CudaDevAttrHostMemoryPoolsSupported:               "CudaDevAttrHostMemoryPoolsSupported",
	CudaDevAttrHostNativeAtomicSupported:              "CudaDevAttrHostNativeAtomicSupported",
	CudaDevAttrHostNumaId:                             "CudaDevAttrHostNumaId",
	CudaDevAttrHostNumaMemoryPoolsSupported:           "CudaDevAttrHostNumaMemoryPoolsSupported",
	CudaDevAttrHostNumaMultinodeIpcSupported:          "CudaDevAttrHostNumaMultinodeIpcSupported",
	CudaDevAttrHostRegisterReadOnlySupported:          "CudaDevAttrHostRegisterReadOnlySupported",
	CudaDevAttrHostRegisterSupported:                  "CudaDevAttrHostRegisterSupported",
	CudaDevAttrIntegrated:                             "CudaDevAttrIntegrated",
	CudaDevAttrIpcEventSupport:                        "CudaDevAttrIpcEventSupport",
	CudaDevAttrIsMultiGpuBoard:                        "CudaDevAttrIsMultiGpuBoard",
	CudaDevAttrKernelExecTimeout:                      "CudaDevAttrKernelExecTimeout",
	CudaDevAttrL2CacheSize:                            "CudaDevAttrL2CacheSize",
	CudaDevAttrLocalL1CacheSupported:                  "CudaDevAttrLocalL1CacheSupported",
	CudaDevAttrManagedMemory:                          "CudaDevAttrManagedMemory",
	CudaDevAttrMaxAccessPolicyWindowSize:              "CudaDevAttrMaxAccessPolicyWindowSize",
	CudaDevAttrMaxBlockDimX:                           "CudaDevAttrMaxBlockDimX",
	CudaDevAttrMaxBlockDimY:                           "CudaDevAttrMaxBlockDimY",
	CudaDevAttrMaxBlockDimZ:                           "CudaDevAttrMaxBlockDimZ",
	CudaDevAttrMaxBlocksPerMultiprocessor:             "CudaDevAttrMaxBlocksPerMultiprocessor",
	CudaDevAttrMaxGridDimX:                            "CudaDevAttrMaxGridDimX",
	CudaDevAttrMaxGridDimY:                            "CudaDevAttrMaxGridDimY",
	CudaDevAttrMaxGridDimZ:                            "CudaDevAttrMaxGridDimZ",
	CudaDevAttrMaxPersistingL2CacheSize:               "CudaDevAttrMaxPersistingL2CacheSize",
	CudaDevAttrMaxPitch:                               "CudaDevAttrMaxPitch",
	CudaDevAttrMaxRegistersPerBlock:                   "CudaDevAttrMaxRegistersPerBlock",
	CudaDevAttrMaxRegistersPerMultiprocessor:          "CudaDevAttrMaxRegistersPerMultiprocessor",
	CudaDevAttrMaxSharedMemoryPerBlock:                "CudaDevAttrMaxSharedMemoryPerBlock",
	CudaDevAttrMaxSharedMemoryPerBlockOptin:           "CudaDevAttrMaxSharedMemoryPerBlockOptin",
	CudaDevAttrMaxSharedMemoryPerMultiprocessor:       "CudaDevAttrMaxSharedMemoryPerMultiprocessor",
	CudaDevAttrMaxSurface1DlayeredLayers:              "CudaDevAttrMaxSurface1DlayeredLayers",
	CudaDevAttrMaxSurface1DlayeredWidth:               "CudaDevAttrMaxSurface1DlayeredWidth",
	CudaDevAttrMaxSurface1Dwidth:                      "CudaDevAttrMaxSurface1Dwidth",
	CudaDevAttrMaxSurface2Dheight:                     "CudaDevAttrMaxSurface2Dheight",
	CudaDevAttrMaxSurface2DlayeredHeight:              "CudaDevAttrMaxSurface2DlayeredHeight",
	CudaDevAttrMaxSurface2DlayeredLayers:              "CudaDevAttrMaxSurface2DlayeredLayers",
	CudaDevAttrMaxSurface2DlayeredWidth:               "CudaDevAttrMaxSurface2DlayeredWidth",
	CudaDevAttrMaxSurface2Dwidth:                      "CudaDevAttrMaxSurface2Dwidth",
	CudaDevAttrMaxSurface3Ddepth:                      "CudaDevAttrMaxSurface3Ddepth",
	CudaDevAttrMaxSurface3Dheight:                     "CudaDevAttrMaxSurface3Dheight",
	CudaDevAttrMaxSurface3Dwidth:                      "CudaDevAttrMaxSurface3Dwidth",
	CudaDevAttrMaxSurfaceCubemapLayeredLayers:         "CudaDevAttrMaxSurfaceCubemapLayeredLayers",
	CudaDevAttrMaxSurfaceCubemapLayeredWidth:          "CudaDevAttrMaxSurfaceCubemapLayeredWidth",
	CudaDevAttrMaxSurfaceCubemapWidth:                 "CudaDevAttrMaxSurfaceCubemapWidth",
	CudaDevAttrMaxTexture1DlayeredLayers:              "CudaDevAttrMaxTexture1DlayeredLayers",
	CudaDevAttrMaxTexture1DlayeredWidth:               "CudaDevAttrMaxTexture1DlayeredWidth",
	CudaDevAttrMaxTexture1DlinearWidth:                "CudaDevAttrMaxTexture1DlinearWidth",
	CudaDevAttrMaxTexture1DmipmappedWidth:             "CudaDevAttrMaxTexture1DmipmappedWidth",
	CudaDevAttrMaxTexture1Dwidth:                      "CudaDevAttrMaxTexture1Dwidth",
	CudaDevAttrMaxTexture2DgatherHeight:               "CudaDevAttrMaxTexture2DgatherHeight",
	CudaDevAttrMaxTexture2DgatherWidth:                "CudaDevAttrMaxTexture2DgatherWidth",
	CudaDevAttrMaxTexture2Dheight:                     "CudaDevAttrMaxTexture2Dheight",
	CudaDevAttrMaxTexture2DlayeredHeight:              "CudaDevAttrMaxTexture2DlayeredHeight",
	CudaDevAttrMaxTexture2DlayeredLayers:              "CudaDevAttrMaxTexture2DlayeredLayers",
	CudaDevAttrMaxTexture2DlayeredWidth:               "CudaDevAttrMaxTexture2DlayeredWidth",
	CudaDevAttrMaxTexture2DlinearHeight:               "CudaDevAttrMaxTexture2DlinearHeight",
	CudaDevAttrMaxTexture2DlinearPitch:                "CudaDevAttrMaxTexture2DlinearPitch",
	CudaDevAttrMaxTexture2DlinearWidth:                "CudaDevAttrMaxTexture2DlinearWidth",
	CudaDevAttrMaxTexture2DmipmappedHeight:            "CudaDevAttrMaxTexture2DmipmappedHeight",
	CudaDevAttrMaxTexture2DmipmappedWidth:             "CudaDevAttrMaxTexture2DmipmappedWidth",
	CudaDevAttrMaxTexture2Dwidth:                      "CudaDevAttrMaxTexture2Dwidth",
	CudaDevAttrMaxTexture3Ddepth:                      "CudaDevAttrMaxTexture3Ddepth",
	CudaDevAttrMaxTexture3DdepthAlt:                   "CudaDevAttrMaxTexture3DdepthAlt",
	CudaDevAttrMaxTexture3Dheight:                     "CudaDevAttrMaxTexture3Dheight",
	CudaDevAttrMaxTexture3DheightAlt:                  "CudaDevAttrMaxTexture3DheightAlt",
	CudaDevAttrMaxTexture3Dwidth:                      "CudaDevAttrMaxTexture3Dwidth",
	CudaDevAttrMaxTexture3DwidthAlt:                   "CudaDevAttrMaxTexture3DwidthAlt",
	CudaDevAttrMaxTextureCubemapLayeredLayers:         "CudaDevAttrMaxTextureCubemapLayeredLayers",
	CudaDevAttrMaxTextureCubemapLayeredWidth:          "CudaDevAttrMaxTextureCubemapLayeredWidth",
	CudaDevAttrMaxTextureCubemapWidth:                 "CudaDevAttrMaxTextureCubemapWidth",
	CudaDevAttrMaxThreadsPerBlock:                     "CudaDevAttrMaxThreadsPerBlock",
	CudaDevAttrMaxThreadsPerMultiProcessor:            "CudaDevAttrMaxThreadsPerMultiProcessor",
	CudaDevAttrMemSyncDomainCount:                     "CudaDevAttrMemSyncDomainCount",
	CudaDevAttrMemoryClockRate:                        "CudaDevAttrMemoryClockRate",
	CudaDevAttrMemoryPoolSupportedHandleTypes:         "CudaDevAttrMemoryPoolSupportedHandleTypes",
	CudaDevAttrMemoryPoolsSupported:                   "CudaDevAttrMemoryPoolsSupported",
	CudaDevAttrMpsEnabled:                             "CudaDevAttrMpsEnabled",
	CudaDevAttrMultiGpuBoardGroupId:                   "CudaDevAttrMultiGpuBoardGroupId",
	CudaDevAttrMultiProcessorCount:                    "CudaDevAttrMultiProcessorCount",
	CudaDevAttrNumaConfig:                             "CudaDevAttrNumaConfig",
	CudaDevAttrNumaId:                                 "CudaDevAttrNumaId",
	CudaDevAttrOnlyPartialHostNativeAtomicSupported:   "CudaDevAttrOnlyPartialHostNativeAtomicSupported",
	CudaDevAttrPageableMemoryAccess:                   "CudaDevAttrPageableMemoryAccess",
	CudaDevAttrPageableMemoryAccessUsesHostPageTables: "CudaDevAttrPageableMemoryAccessUsesHostPageTables",
	CudaDevAttrPciBusId:                               "CudaDevAttrPciBusId",
	CudaDevAttrPciDeviceId:                            "CudaDevAttrPciDeviceId",
	CudaDevAttrPciDomainId:                            "CudaDevAttrPciDomainId",
	CudaDevAttrReserved122:                            "CudaDevAttrReserved122",
	CudaDevAttrReserved123:                            "CudaDevAttrReserved123",
	CudaDevAttrReserved124:                            "CudaDevAttrReserved124",
	CudaDevAttrReserved127:                            "CudaDevAttrReserved127",
	CudaDevAttrReserved128:                            "CudaDevAttrReserved128",
	CudaDevAttrReserved129:                            "CudaDevAttrReserved129",
	CudaDevAttrReserved132:                            "CudaDevAttrReserved132",
	CudaDevAttrReserved141:                            "CudaDevAttrReserved141",
	CudaDevAttrReserved145:                            "CudaDevAttrReserved145",
	CudaDevAttrReserved92:                             "CudaDevAttrReserved92",
	CudaDevAttrReserved93:                             "CudaDevAttrReserved93",
	CudaDevAttrReserved94:                             "CudaDevAttrReserved94",
	CudaDevAttrReserved96:                             "CudaDevAttrReserved96",
	CudaDevAttrReservedSharedMemoryPerBlock:           "CudaDevAttrReservedSharedMemoryPerBlock",
	CudaDevAttrSingleToDoublePrecisionPerfRatio:       "CudaDevAttrSingleToDoublePrecisionPerfRatio",
	CudaDevAttrSparseCudaArraySupported:               "CudaDevAttrSparseCudaArraySupported",
	CudaDevAttrStreamPrioritiesSupported:              "CudaDevAttrStreamPrioritiesSupported",
	CudaDevAttrSurfaceAlignment:                       "CudaDevAttrSurfaceAlignment",
	CudaDevAttrTccDriver:                              "CudaDevAttrTccDriver",
	CudaDevAttrTextureAlignment:                       "CudaDevAttrTextureAlignment",
	CudaDevAttrTexturePitchAlignment:                  "CudaDevAttrTexturePitchAlignment",
	CudaDevAttrTimelineSemaphoreInteropSupported:      "CudaDevAttrTimelineSemaphoreInteropSupported",
	CudaDevAttrTotalConstantMemory:                    "CudaDevAttrTotalConstantMemory",
	CudaDevAttrUnifiedAddressing:                      "CudaDevAttrUnifiedAddressing",
	CudaDevAttrVulkanCigSupported:                     "CudaDevAttrVulkanCigSupported",
	CudaDevAttrWarpSize:                               "CudaDevAttrWarpSize",
}
