// Code generated by generator.go; DO NOT EDIT.
//go:build cuda12
// +build cuda12

package cudart

/*
#include <cuda_runtime.h>
*/
import "C"

// Constants for CudaLimit.
const (
	CudaLimitDevRuntimePendingLaunchCount CudaLimit = C.cudaLimitDevRuntimePendingLaunchCount
	CudaLimitDevRuntimeSyncDepth          CudaLimit = C.cudaLimitDevRuntimeSyncDepth
	CudaLimitMallocHeapSize               CudaLimit = C.cudaLimitMallocHeapSize
	CudaLimitMaxL2FetchGranularity        CudaLimit = C.cudaLimitMaxL2FetchGranularity
	CudaLimitPersistingL2CacheSize        CudaLimit = C.cudaLimitPersistingL2CacheSize
	CudaLimitPrintfFifoSize               CudaLimit = C.cudaLimitPrintfFifoSize
	CudaLimitStackSize                    CudaLimit = C.cudaLimitStackSize
)

// CudaLimitMessages maps CudaLimit values to their string representations.
var CudaLimitMessages = map[CudaLimit]string{
	CudaLimitDevRuntimePendingLaunchCount: "CudaLimitDevRuntimePendingLaunchCount",
	CudaLimitDevRuntimeSyncDepth:          "CudaLimitDevRuntimeSyncDepth",
	CudaLimitMallocHeapSize:               "CudaLimitMallocHeapSize",
	CudaLimitMaxL2FetchGranularity:        "CudaLimitMaxL2FetchGranularity",
	CudaLimitPersistingL2CacheSize:        "CudaLimitPersistingL2CacheSize",
	CudaLimitPrintfFifoSize:               "CudaLimitPrintfFifoSize",
	CudaLimitStackSize:                    "CudaLimitStackSize",
}
