// Code generated by generator.go; DO NOT EDIT.
//go:build cuda13
// +build cuda13

package cudart

/*
#include <cuda_runtime.h>
*/
import "C"

// Constants for DeviceAttr.
const (
	CudaDevAttrAsyncEngineCount                       DeviceAttr = C.cudaDevAttrAsyncEngineCount                       // < Number of asynchronous engines
	CudaDevAttrCanFlushRemoteWrites                   DeviceAttr = C.cudaDevAttrCanFlushRemoteWrites                   // < Device supports flushing of outstanding remote writes.
	CudaDevAttrCanMapHostMemory                       DeviceAttr = C.cudaDevAttrCanMapHostMemory                       // < Device can map host memory into CUDA address space
	CudaDevAttrCanUseHostPointerForRegisteredMem      DeviceAttr = C.cudaDevAttrCanUseHostPointerForRegisteredMem      // < Device can access host registered memory at the same virtual address as the CPU
	CudaDevAttrClockRate                              DeviceAttr = C.cudaDevAttrClockRate                              // < Peak clock frequency in kilohertz
	CudaDevAttrClusterLaunch                          DeviceAttr = C.cudaDevAttrClusterLaunch                          // < Indicates device supports cluster launch
	CudaDevAttrComputeCapabilityMajor                 DeviceAttr = C.cudaDevAttrComputeCapabilityMajor                 // < Major compute capability version number
	CudaDevAttrComputeCapabilityMinor                 DeviceAttr = C.cudaDevAttrComputeCapabilityMinor                 // < Minor compute capability version number
	CudaDevAttrComputeMode                            DeviceAttr = C.cudaDevAttrComputeMode                            // < Compute mode (See ::cudaComputeMode for details)
	CudaDevAttrComputePreemptionSupported             DeviceAttr = C.cudaDevAttrComputePreemptionSupported             // < Device supports Compute Preemption
	CudaDevAttrConcurrentKernels                      DeviceAttr = C.cudaDevAttrConcurrentKernels                      // < Device can possibly execute multiple kernels concurrently
	CudaDevAttrConcurrentManagedAccess                DeviceAttr = C.cudaDevAttrConcurrentManagedAccess                // < Device can coherently access managed memory concurrently with the CPU
	CudaDevAttrCooperativeLaunch                      DeviceAttr = C.cudaDevAttrCooperativeLaunch                      // < Device supports launching cooperative kernels via ::cudaLaunchCooperativeKernel
	CudaDevAttrD3d12cigSupported                      DeviceAttr = C.cudaDevAttrD3D12CigSupported                      // < Device supports CIG with D3D12.
	CudaDevAttrDeferredMappingCudaArraySupported      DeviceAttr = C.cudaDevAttrDeferredMappingCudaArraySupported      // < Device supports deferred mapping CUDA arrays and CUDA mipmapped arrays
	CudaDevAttrDirectManagedMemAccessFromHost         DeviceAttr = C.cudaDevAttrDirectManagedMemAccessFromHost         // < Host can directly access managed memory on the device without migration.
	CudaDevAttrEccEnabled                             DeviceAttr = C.cudaDevAttrEccEnabled                             // < Device has ECC support enabled
	CudaDevAttrGpudirectRdmaflushWritesOptions        DeviceAttr = C.cudaDevAttrGPUDirectRDMAFlushWritesOptions        // < The returned attribute shall be interpreted as a bitmask, where the individual bits are listed in the ::cudaFlushGPUDirectRDMAWritesOptions enum
	CudaDevAttrGpudirectRdmasupported                 DeviceAttr = C.cudaDevAttrGPUDirectRDMASupported                 // < Device supports GPUDirect RDMA APIs, like nvidia_p2p_get_pages (see https://docs.nvidia.com/cuda/gpudirect-rdma for more information)
	CudaDevAttrGpudirectRdmawritesOrdering            DeviceAttr = C.cudaDevAttrGPUDirectRDMAWritesOrdering            // < GPUDirect RDMA writes to the device do not need to be flushed for consumers within the scope indicated by the returned attribute. See ::cudaGPUDirectRDMAWritesOrdering for the numerical values returned here.
	CudaDevAttrGlobalL1cacheSupported                 DeviceAttr = C.cudaDevAttrGlobalL1CacheSupported                 // < Device supports caching globals in L1
	CudaDevAttrGlobalMemoryBusWidth                   DeviceAttr = C.cudaDevAttrGlobalMemoryBusWidth                   // < Global memory bus width in bits
	CudaDevAttrGpuOverlap                             DeviceAttr = C.cudaDevAttrGpuOverlap                             // < Device can possibly copy memory and execute a kernel concurrently
	CudaDevAttrGpuPciDeviceId                         DeviceAttr = C.cudaDevAttrGpuPciDeviceId                         // < The combined 16-bit PCI device ID and 16-bit PCI vendor ID.
	CudaDevAttrGpuPciSubsystemId                      DeviceAttr = C.cudaDevAttrGpuPciSubsystemId                      // < The combined 16-bit PCI subsystem ID and 16-bit PCI subsystem vendor ID.
	CudaDevAttrHostMemoryPoolsSupported               DeviceAttr = C.cudaDevAttrHostMemoryPoolsSupported               // < Device suports HOST location with the ::cuMemAllocAsync and ::cuMemPool family of APIs
	CudaDevAttrHostNativeAtomicSupported              DeviceAttr = C.cudaDevAttrHostNativeAtomicSupported              // < Link between the device and the host supports native atomic operations
	CudaDevAttrHostNumaId                             DeviceAttr = C.cudaDevAttrHostNumaId                             // < NUMA ID of the host node closest to the device or -1 when system does not support NUMA
	CudaDevAttrHostNumaMemoryPoolsSupported           DeviceAttr = C.cudaDevAttrHostNumaMemoryPoolsSupported           // < Device supports HOST_NUMA location with the ::cudaMallocAsync and ::cudaMemPool family of APIs
	CudaDevAttrHostNumaMultinodeIpcSupported          DeviceAttr = C.cudaDevAttrHostNumaMultinodeIpcSupported          // < Device supports HostNuma location IPC between nodes in a multi-node system.
	CudaDevAttrHostRegisterReadOnlySupported          DeviceAttr = C.cudaDevAttrHostRegisterReadOnlySupported          // < Device supports using the ::cudaHostRegister flag cudaHostRegisterReadOnly to register memory that must be mapped as read-only to the GPU
	CudaDevAttrHostRegisterSupported                  DeviceAttr = C.cudaDevAttrHostRegisterSupported                  // < Device supports host memory registration via ::cudaHostRegister.
	CudaDevAttrIntegrated                             DeviceAttr = C.cudaDevAttrIntegrated                             // < Device is integrated with host memory
	CudaDevAttrIpcEventSupport                        DeviceAttr = C.cudaDevAttrIpcEventSupport                        // < Device supports IPC Events.
	CudaDevAttrIsMultiGpuBoard                        DeviceAttr = C.cudaDevAttrIsMultiGpuBoard                        // < Device is on a multi-GPU board
	CudaDevAttrKernelExecTimeout                      DeviceAttr = C.cudaDevAttrKernelExecTimeout                      // < Specifies whether there is a run time limit on kernels
	CudaDevAttrL2cacheSize                            DeviceAttr = C.cudaDevAttrL2CacheSize                            // < Size of L2 cache in bytes
	CudaDevAttrLocalL1cacheSupported                  DeviceAttr = C.cudaDevAttrLocalL1CacheSupported                  // < Device supports caching locals in L1
	CudaDevAttrManagedMemory                          DeviceAttr = C.cudaDevAttrManagedMemory                          // < Device can allocate managed memory on this system
	CudaDevAttrMaxAccessPolicyWindowSize              DeviceAttr = C.cudaDevAttrMaxAccessPolicyWindowSize              // < Maximum value of cudaAccessPolicyWindow::num_bytes.
	CudaDevAttrMaxBlockDimX                           DeviceAttr = C.cudaDevAttrMaxBlockDimX                           // < Maximum block dimension X
	CudaDevAttrMaxBlockDimY                           DeviceAttr = C.cudaDevAttrMaxBlockDimY                           // < Maximum block dimension Y
	CudaDevAttrMaxBlockDimZ                           DeviceAttr = C.cudaDevAttrMaxBlockDimZ                           // < Maximum block dimension Z
	CudaDevAttrMaxBlocksPerMultiprocessor             DeviceAttr = C.cudaDevAttrMaxBlocksPerMultiprocessor             // < Maximum number of blocks per multiprocessor
	CudaDevAttrMaxGridDimX                            DeviceAttr = C.cudaDevAttrMaxGridDimX                            // < Maximum grid dimension X
	CudaDevAttrMaxGridDimY                            DeviceAttr = C.cudaDevAttrMaxGridDimY                            // < Maximum grid dimension Y
	CudaDevAttrMaxGridDimZ                            DeviceAttr = C.cudaDevAttrMaxGridDimZ                            // < Maximum grid dimension Z
	CudaDevAttrMaxPersistingL2cacheSize               DeviceAttr = C.cudaDevAttrMaxPersistingL2CacheSize               // < Maximum L2 persisting lines capacity setting in bytes.
	CudaDevAttrMaxPitch                               DeviceAttr = C.cudaDevAttrMaxPitch                               // < Maximum pitch in bytes allowed by memory copies
	CudaDevAttrMaxRegistersPerBlock                   DeviceAttr = C.cudaDevAttrMaxRegistersPerBlock                   // < Maximum number of 32-bit registers available per block
	CudaDevAttrMaxRegistersPerMultiprocessor          DeviceAttr = C.cudaDevAttrMaxRegistersPerMultiprocessor          // < Maximum number of 32-bit registers available per multiprocessor
	CudaDevAttrMaxSharedMemoryPerBlock                DeviceAttr = C.cudaDevAttrMaxSharedMemoryPerBlock                // < Maximum shared memory available per block in bytes
	CudaDevAttrMaxSharedMemoryPerBlockOptin           DeviceAttr = C.cudaDevAttrMaxSharedMemoryPerBlockOptin           // < The maximum optin shared memory per block. This value may vary by chip. See ::cudaFuncSetAttribute
	CudaDevAttrMaxSharedMemoryPerMultiprocessor       DeviceAttr = C.cudaDevAttrMaxSharedMemoryPerMultiprocessor       // < Maximum shared memory available per multiprocessor in bytes
	CudaDevAttrMaxSurface1dlayeredLayers              DeviceAttr = C.cudaDevAttrMaxSurface1DLayeredLayers              // < Maximum layers in a 1D layered surface
	CudaDevAttrMaxSurface1dlayeredWidth               DeviceAttr = C.cudaDevAttrMaxSurface1DLayeredWidth               // < Maximum 1D layered surface width
	CudaDevAttrMaxSurface1dwidth                      DeviceAttr = C.cudaDevAttrMaxSurface1DWidth                      // < Maximum 1D surface width
	CudaDevAttrMaxSurface2dheight                     DeviceAttr = C.cudaDevAttrMaxSurface2DHeight                     // < Maximum 2D surface height
	CudaDevAttrMaxSurface2dlayeredHeight              DeviceAttr = C.cudaDevAttrMaxSurface2DLayeredHeight              // < Maximum 2D layered surface height
	CudaDevAttrMaxSurface2dlayeredLayers              DeviceAttr = C.cudaDevAttrMaxSurface2DLayeredLayers              // < Maximum layers in a 2D layered surface
	CudaDevAttrMaxSurface2dlayeredWidth               DeviceAttr = C.cudaDevAttrMaxSurface2DLayeredWidth               // < Maximum 2D layered surface width
	CudaDevAttrMaxSurface2dwidth                      DeviceAttr = C.cudaDevAttrMaxSurface2DWidth                      // < Maximum 2D surface width
	CudaDevAttrMaxSurface3ddepth                      DeviceAttr = C.cudaDevAttrMaxSurface3DDepth                      // < Maximum 3D surface depth
	CudaDevAttrMaxSurface3dheight                     DeviceAttr = C.cudaDevAttrMaxSurface3DHeight                     // < Maximum 3D surface height
	CudaDevAttrMaxSurface3dwidth                      DeviceAttr = C.cudaDevAttrMaxSurface3DWidth                      // < Maximum 3D surface width
	CudaDevAttrMaxSurfaceCubemapLayeredLayers         DeviceAttr = C.cudaDevAttrMaxSurfaceCubemapLayeredLayers         // < Maximum layers in a cubemap layered surface
	CudaDevAttrMaxSurfaceCubemapLayeredWidth          DeviceAttr = C.cudaDevAttrMaxSurfaceCubemapLayeredWidth          // < Maximum cubemap layered surface width
	CudaDevAttrMaxSurfaceCubemapWidth                 DeviceAttr = C.cudaDevAttrMaxSurfaceCubemapWidth                 // < Maximum cubemap surface width
	CudaDevAttrMaxTexture1dlayeredLayers              DeviceAttr = C.cudaDevAttrMaxTexture1DLayeredLayers              // < Maximum layers in a 1D layered texture
	CudaDevAttrMaxTexture1dlayeredWidth               DeviceAttr = C.cudaDevAttrMaxTexture1DLayeredWidth               // < Maximum 1D layered texture width
	CudaDevAttrMaxTexture1dlinearWidth                DeviceAttr = C.cudaDevAttrMaxTexture1DLinearWidth                // < Maximum 1D linear texture width
	CudaDevAttrMaxTexture1dmipmappedWidth             DeviceAttr = C.cudaDevAttrMaxTexture1DMipmappedWidth             // < Maximum mipmapped 1D texture width
	CudaDevAttrMaxTexture1dwidth                      DeviceAttr = C.cudaDevAttrMaxTexture1DWidth                      // < Maximum 1D texture width
	CudaDevAttrMaxTexture2dgatherHeight               DeviceAttr = C.cudaDevAttrMaxTexture2DGatherHeight               // < Maximum 2D texture height if cudaArrayTextureGather is set
	CudaDevAttrMaxTexture2dgatherWidth                DeviceAttr = C.cudaDevAttrMaxTexture2DGatherWidth                // < Maximum 2D texture width if cudaArrayTextureGather is set
	CudaDevAttrMaxTexture2dheight                     DeviceAttr = C.cudaDevAttrMaxTexture2DHeight                     // < Maximum 2D texture height
	CudaDevAttrMaxTexture2dlayeredHeight              DeviceAttr = C.cudaDevAttrMaxTexture2DLayeredHeight              // < Maximum 2D layered texture height
	CudaDevAttrMaxTexture2dlayeredLayers              DeviceAttr = C.cudaDevAttrMaxTexture2DLayeredLayers              // < Maximum layers in a 2D layered texture
	CudaDevAttrMaxTexture2dlayeredWidth               DeviceAttr = C.cudaDevAttrMaxTexture2DLayeredWidth               // < Maximum 2D layered texture width
	CudaDevAttrMaxTexture2dlinearHeight               DeviceAttr = C.cudaDevAttrMaxTexture2DLinearHeight               // < Maximum 2D linear texture height
	CudaDevAttrMaxTexture2dlinearPitch                DeviceAttr = C.cudaDevAttrMaxTexture2DLinearPitch                // < Maximum 2D linear texture pitch in bytes
	CudaDevAttrMaxTexture2dlinearWidth                DeviceAttr = C.cudaDevAttrMaxTexture2DLinearWidth                // < Maximum 2D linear texture width
	CudaDevAttrMaxTexture2dmipmappedHeight            DeviceAttr = C.cudaDevAttrMaxTexture2DMipmappedHeight            // < Maximum mipmapped 2D texture height
	CudaDevAttrMaxTexture2dmipmappedWidth             DeviceAttr = C.cudaDevAttrMaxTexture2DMipmappedWidth             // < Maximum mipmapped 2D texture width
	CudaDevAttrMaxTexture2dwidth                      DeviceAttr = C.cudaDevAttrMaxTexture2DWidth                      // < Maximum 2D texture width
	CudaDevAttrMaxTexture3ddepth                      DeviceAttr = C.cudaDevAttrMaxTexture3DDepth                      // < Maximum 3D texture depth
	CudaDevAttrMaxTexture3ddepthAlt                   DeviceAttr = C.cudaDevAttrMaxTexture3DDepthAlt                   // < Alternate maximum 3D texture depth
	CudaDevAttrMaxTexture3dheight                     DeviceAttr = C.cudaDevAttrMaxTexture3DHeight                     // < Maximum 3D texture height
	CudaDevAttrMaxTexture3dheightAlt                  DeviceAttr = C.cudaDevAttrMaxTexture3DHeightAlt                  // < Alternate maximum 3D texture height
	CudaDevAttrMaxTexture3dwidth                      DeviceAttr = C.cudaDevAttrMaxTexture3DWidth                      // < Maximum 3D texture width
	CudaDevAttrMaxTexture3dwidthAlt                   DeviceAttr = C.cudaDevAttrMaxTexture3DWidthAlt                   // < Alternate maximum 3D texture width
	CudaDevAttrMaxTextureCubemapLayeredLayers         DeviceAttr = C.cudaDevAttrMaxTextureCubemapLayeredLayers         // < Maximum layers in a cubemap layered texture
	CudaDevAttrMaxTextureCubemapLayeredWidth          DeviceAttr = C.cudaDevAttrMaxTextureCubemapLayeredWidth          // < Maximum cubemap layered texture width/height
	CudaDevAttrMaxTextureCubemapWidth                 DeviceAttr = C.cudaDevAttrMaxTextureCubemapWidth                 // < Maximum cubemap texture width/height
	CudaDevAttrMaxThreadsPerBlock                     DeviceAttr = C.cudaDevAttrMaxThreadsPerBlock                     // < Maximum number of threads per block
	CudaDevAttrMaxThreadsPerMultiProcessor            DeviceAttr = C.cudaDevAttrMaxThreadsPerMultiProcessor            // < Maximum resident threads per multiprocessor
	CudaDevAttrMemSyncDomainCount                     DeviceAttr = C.cudaDevAttrMemSyncDomainCount                     // < Number of memory synchronization domains the device supports.
	CudaDevAttrMemoryClockRate                        DeviceAttr = C.cudaDevAttrMemoryClockRate                        // < Peak memory clock frequency in kilohertz
	CudaDevAttrMemoryPoolSupportedHandleTypes         DeviceAttr = C.cudaDevAttrMemoryPoolSupportedHandleTypes         // < Handle types supported with mempool based IPC
	CudaDevAttrMemoryPoolsSupported                   DeviceAttr = C.cudaDevAttrMemoryPoolsSupported                   // < Device supports using the ::cudaMallocAsync and ::cudaMemPool family of APIs
	CudaDevAttrMpsEnabled                             DeviceAttr = C.cudaDevAttrMpsEnabled                             // < Contexts created on this device will be shared via MPS
	CudaDevAttrMultiGpuBoardGroupId                   DeviceAttr = C.cudaDevAttrMultiGpuBoardGroupID                   // < Unique identifier for a group of devices on the same multi-GPU board
	CudaDevAttrMultiProcessorCount                    DeviceAttr = C.cudaDevAttrMultiProcessorCount                    // < Number of multiprocessors on device
	CudaDevAttrNumaConfig                             DeviceAttr = C.cudaDevAttrNumaConfig                             // < NUMA configuration of a device: value is of type ::cudaDeviceNumaConfig enum
	CudaDevAttrNumaId                                 DeviceAttr = C.cudaDevAttrNumaId                                 // < NUMA node ID of the GPU memory
	CudaDevAttrOnlyPartialHostNativeAtomicSupported   DeviceAttr = C.cudaDevAttrOnlyPartialHostNativeAtomicSupported   // < Link between the device and the host supports only some native atomic operations
	CudaDevAttrPageableMemoryAccess                   DeviceAttr = C.cudaDevAttrPageableMemoryAccess                   // < Device supports coherently accessing pageable memory without calling cudaHostRegister on it
	CudaDevAttrPageableMemoryAccessUsesHostPageTables DeviceAttr = C.cudaDevAttrPageableMemoryAccessUsesHostPageTables // < Device accesses pageable memory via the host's page tables.
	CudaDevAttrPciBusId                               DeviceAttr = C.cudaDevAttrPciBusId                               // < PCI bus ID of the device
	CudaDevAttrPciDeviceId                            DeviceAttr = C.cudaDevAttrPciDeviceId                            // < PCI device ID of the device
	CudaDevAttrPciDomainId                            DeviceAttr = C.cudaDevAttrPciDomainId                            // < PCI domain ID of the device
	CudaDevAttrReserved122                            DeviceAttr = C.cudaDevAttrReserved122
	CudaDevAttrReserved123                            DeviceAttr = C.cudaDevAttrReserved123
	CudaDevAttrReserved124                            DeviceAttr = C.cudaDevAttrReserved124
	CudaDevAttrReserved127                            DeviceAttr = C.cudaDevAttrReserved127
	CudaDevAttrReserved128                            DeviceAttr = C.cudaDevAttrReserved128
	CudaDevAttrReserved129                            DeviceAttr = C.cudaDevAttrReserved129
	CudaDevAttrReserved132                            DeviceAttr = C.cudaDevAttrReserved132
	CudaDevAttrReserved141                            DeviceAttr = C.cudaDevAttrReserved141
	CudaDevAttrReserved145                            DeviceAttr = C.cudaDevAttrReserved145
	CudaDevAttrReserved92                             DeviceAttr = C.cudaDevAttrReserved92
	CudaDevAttrReserved93                             DeviceAttr = C.cudaDevAttrReserved93
	CudaDevAttrReserved94                             DeviceAttr = C.cudaDevAttrReserved94
	CudaDevAttrReserved96                             DeviceAttr = C.cudaDevAttrReserved96
	CudaDevAttrReservedSharedMemoryPerBlock           DeviceAttr = C.cudaDevAttrReservedSharedMemoryPerBlock      // < Shared memory reserved by CUDA driver per block in bytes
	CudaDevAttrSingleToDoublePrecisionPerfRatio       DeviceAttr = C.cudaDevAttrSingleToDoublePrecisionPerfRatio  // < Ratio of single precision performance (in floating-point operations per second) to double precision performance
	CudaDevAttrSparseCudaArraySupported               DeviceAttr = C.cudaDevAttrSparseCudaArraySupported          // < Device supports sparse CUDA arrays and sparse CUDA mipmapped arrays
	CudaDevAttrStreamPrioritiesSupported              DeviceAttr = C.cudaDevAttrStreamPrioritiesSupported         // < Device supports stream priorities
	CudaDevAttrSurfaceAlignment                       DeviceAttr = C.cudaDevAttrSurfaceAlignment                  // < Alignment requirement for surfaces
	CudaDevAttrTccDriver                              DeviceAttr = C.cudaDevAttrTccDriver                         // < Device is using TCC driver model
	CudaDevAttrTextureAlignment                       DeviceAttr = C.cudaDevAttrTextureAlignment                  // < Alignment requirement for textures
	CudaDevAttrTexturePitchAlignment                  DeviceAttr = C.cudaDevAttrTexturePitchAlignment             // < Pitch alignment requirement for textures
	CudaDevAttrTimelineSemaphoreInteropSupported      DeviceAttr = C.cudaDevAttrTimelineSemaphoreInteropSupported // < External timeline semaphore interop is supported on the device
	CudaDevAttrTotalConstantMemory                    DeviceAttr = C.cudaDevAttrTotalConstantMemory               // < Memory available on device for __constant__ variables in a CUDA C kernel in bytes
	CudaDevAttrUnifiedAddressing                      DeviceAttr = C.cudaDevAttrUnifiedAddressing                 // < Device shares a unified address space with the host
	CudaDevAttrVulkanCigSupported                     DeviceAttr = C.cudaDevAttrVulkanCigSupported                // < Device supports CIG with Vulkan.
	CudaDevAttrWarpSize                               DeviceAttr = C.cudaDevAttrWarpSize                          // < Warp size in threads
)

// DeviceAttrMessages maps DeviceAttr values to their string representations.
var DeviceAttrMessages = map[DeviceAttr]string{
	CudaDevAttrAsyncEngineCount:                       "CudaDevAttrAsyncEngineCount",
	CudaDevAttrCanFlushRemoteWrites:                   "CudaDevAttrCanFlushRemoteWrites",
	CudaDevAttrCanMapHostMemory:                       "CudaDevAttrCanMapHostMemory",
	CudaDevAttrCanUseHostPointerForRegisteredMem:      "CudaDevAttrCanUseHostPointerForRegisteredMem",
	CudaDevAttrClockRate:                              "CudaDevAttrClockRate",
	CudaDevAttrClusterLaunch:                          "CudaDevAttrClusterLaunch",
	CudaDevAttrComputeCapabilityMajor:                 "CudaDevAttrComputeCapabilityMajor",
	CudaDevAttrComputeCapabilityMinor:                 "CudaDevAttrComputeCapabilityMinor",
	CudaDevAttrComputeMode:                            "CudaDevAttrComputeMode",
	CudaDevAttrComputePreemptionSupported:             "CudaDevAttrComputePreemptionSupported",
	CudaDevAttrConcurrentKernels:                      "CudaDevAttrConcurrentKernels",
	CudaDevAttrConcurrentManagedAccess:                "CudaDevAttrConcurrentManagedAccess",
	CudaDevAttrCooperativeLaunch:                      "CudaDevAttrCooperativeLaunch",
	CudaDevAttrD3d12cigSupported:                      "CudaDevAttrD3d12cigSupported",
	CudaDevAttrDeferredMappingCudaArraySupported:      "CudaDevAttrDeferredMappingCudaArraySupported",
	CudaDevAttrDirectManagedMemAccessFromHost:         "CudaDevAttrDirectManagedMemAccessFromHost",
	CudaDevAttrEccEnabled:                             "CudaDevAttrEccEnabled",
	CudaDevAttrGpudirectRdmaflushWritesOptions:        "CudaDevAttrGpudirectRdmaflushWritesOptions",
	CudaDevAttrGpudirectRdmasupported:                 "CudaDevAttrGpudirectRdmasupported",
	CudaDevAttrGpudirectRdmawritesOrdering:            "CudaDevAttrGpudirectRdmawritesOrdering",
	CudaDevAttrGlobalL1cacheSupported:                 "CudaDevAttrGlobalL1cacheSupported",
	CudaDevAttrGlobalMemoryBusWidth:                   "CudaDevAttrGlobalMemoryBusWidth",
	CudaDevAttrGpuOverlap:                             "CudaDevAttrGpuOverlap",
	CudaDevAttrGpuPciDeviceId:                         "CudaDevAttrGpuPciDeviceId",
	CudaDevAttrGpuPciSubsystemId:                      "CudaDevAttrGpuPciSubsystemId",
	CudaDevAttrHostMemoryPoolsSupported:               "CudaDevAttrHostMemoryPoolsSupported",
	CudaDevAttrHostNativeAtomicSupported:              "CudaDevAttrHostNativeAtomicSupported",
	CudaDevAttrHostNumaId:                             "CudaDevAttrHostNumaId",
	CudaDevAttrHostNumaMemoryPoolsSupported:           "CudaDevAttrHostNumaMemoryPoolsSupported",
	CudaDevAttrHostNumaMultinodeIpcSupported:          "CudaDevAttrHostNumaMultinodeIpcSupported",
	CudaDevAttrHostRegisterReadOnlySupported:          "CudaDevAttrHostRegisterReadOnlySupported",
	CudaDevAttrHostRegisterSupported:                  "CudaDevAttrHostRegisterSupported",
	CudaDevAttrIntegrated:                             "CudaDevAttrIntegrated",
	CudaDevAttrIpcEventSupport:                        "CudaDevAttrIpcEventSupport",
	CudaDevAttrIsMultiGpuBoard:                        "CudaDevAttrIsMultiGpuBoard",
	CudaDevAttrKernelExecTimeout:                      "CudaDevAttrKernelExecTimeout",
	CudaDevAttrL2cacheSize:                            "CudaDevAttrL2cacheSize",
	CudaDevAttrLocalL1cacheSupported:                  "CudaDevAttrLocalL1cacheSupported",
	CudaDevAttrManagedMemory:                          "CudaDevAttrManagedMemory",
	CudaDevAttrMaxAccessPolicyWindowSize:              "CudaDevAttrMaxAccessPolicyWindowSize",
	CudaDevAttrMaxBlockDimX:                           "CudaDevAttrMaxBlockDimX",
	CudaDevAttrMaxBlockDimY:                           "CudaDevAttrMaxBlockDimY",
	CudaDevAttrMaxBlockDimZ:                           "CudaDevAttrMaxBlockDimZ",
	CudaDevAttrMaxBlocksPerMultiprocessor:             "CudaDevAttrMaxBlocksPerMultiprocessor",
	CudaDevAttrMaxGridDimX:                            "CudaDevAttrMaxGridDimX",
	CudaDevAttrMaxGridDimY:                            "CudaDevAttrMaxGridDimY",
	CudaDevAttrMaxGridDimZ:                            "CudaDevAttrMaxGridDimZ",
	CudaDevAttrMaxPersistingL2cacheSize:               "CudaDevAttrMaxPersistingL2cacheSize",
	CudaDevAttrMaxPitch:                               "CudaDevAttrMaxPitch",
	CudaDevAttrMaxRegistersPerBlock:                   "CudaDevAttrMaxRegistersPerBlock",
	CudaDevAttrMaxRegistersPerMultiprocessor:          "CudaDevAttrMaxRegistersPerMultiprocessor",
	CudaDevAttrMaxSharedMemoryPerBlock:                "CudaDevAttrMaxSharedMemoryPerBlock",
	CudaDevAttrMaxSharedMemoryPerBlockOptin:           "CudaDevAttrMaxSharedMemoryPerBlockOptin",
	CudaDevAttrMaxSharedMemoryPerMultiprocessor:       "CudaDevAttrMaxSharedMemoryPerMultiprocessor",
	CudaDevAttrMaxSurface1dlayeredLayers:              "CudaDevAttrMaxSurface1dlayeredLayers",
	CudaDevAttrMaxSurface1dlayeredWidth:               "CudaDevAttrMaxSurface1dlayeredWidth",
	CudaDevAttrMaxSurface1dwidth:                      "CudaDevAttrMaxSurface1dwidth",
	CudaDevAttrMaxSurface2dheight:                     "CudaDevAttrMaxSurface2dheight",
	CudaDevAttrMaxSurface2dlayeredHeight:              "CudaDevAttrMaxSurface2dlayeredHeight",
	CudaDevAttrMaxSurface2dlayeredLayers:              "CudaDevAttrMaxSurface2dlayeredLayers",
	CudaDevAttrMaxSurface2dlayeredWidth:               "CudaDevAttrMaxSurface2dlayeredWidth",
	CudaDevAttrMaxSurface2dwidth:                      "CudaDevAttrMaxSurface2dwidth",
	CudaDevAttrMaxSurface3ddepth:                      "CudaDevAttrMaxSurface3ddepth",
	CudaDevAttrMaxSurface3dheight:                     "CudaDevAttrMaxSurface3dheight",
	CudaDevAttrMaxSurface3dwidth:                      "CudaDevAttrMaxSurface3dwidth",
	CudaDevAttrMaxSurfaceCubemapLayeredLayers:         "CudaDevAttrMaxSurfaceCubemapLayeredLayers",
	CudaDevAttrMaxSurfaceCubemapLayeredWidth:          "CudaDevAttrMaxSurfaceCubemapLayeredWidth",
	CudaDevAttrMaxSurfaceCubemapWidth:                 "CudaDevAttrMaxSurfaceCubemapWidth",
	CudaDevAttrMaxTexture1dlayeredLayers:              "CudaDevAttrMaxTexture1dlayeredLayers",
	CudaDevAttrMaxTexture1dlayeredWidth:               "CudaDevAttrMaxTexture1dlayeredWidth",
	CudaDevAttrMaxTexture1dlinearWidth:                "CudaDevAttrMaxTexture1dlinearWidth",
	CudaDevAttrMaxTexture1dmipmappedWidth:             "CudaDevAttrMaxTexture1dmipmappedWidth",
	CudaDevAttrMaxTexture1dwidth:                      "CudaDevAttrMaxTexture1dwidth",
	CudaDevAttrMaxTexture2dgatherHeight:               "CudaDevAttrMaxTexture2dgatherHeight",
	CudaDevAttrMaxTexture2dgatherWidth:                "CudaDevAttrMaxTexture2dgatherWidth",
	CudaDevAttrMaxTexture2dheight:                     "CudaDevAttrMaxTexture2dheight",
	CudaDevAttrMaxTexture2dlayeredHeight:              "CudaDevAttrMaxTexture2dlayeredHeight",
	CudaDevAttrMaxTexture2dlayeredLayers:              "CudaDevAttrMaxTexture2dlayeredLayers",
	CudaDevAttrMaxTexture2dlayeredWidth:               "CudaDevAttrMaxTexture2dlayeredWidth",
	CudaDevAttrMaxTexture2dlinearHeight:               "CudaDevAttrMaxTexture2dlinearHeight",
	CudaDevAttrMaxTexture2dlinearPitch:                "CudaDevAttrMaxTexture2dlinearPitch",
	CudaDevAttrMaxTexture2dlinearWidth:                "CudaDevAttrMaxTexture2dlinearWidth",
	CudaDevAttrMaxTexture2dmipmappedHeight:            "CudaDevAttrMaxTexture2dmipmappedHeight",
	CudaDevAttrMaxTexture2dmipmappedWidth:             "CudaDevAttrMaxTexture2dmipmappedWidth",
	CudaDevAttrMaxTexture2dwidth:                      "CudaDevAttrMaxTexture2dwidth",
	CudaDevAttrMaxTexture3ddepth:                      "CudaDevAttrMaxTexture3ddepth",
	CudaDevAttrMaxTexture3ddepthAlt:                   "CudaDevAttrMaxTexture3ddepthAlt",
	CudaDevAttrMaxTexture3dheight:                     "CudaDevAttrMaxTexture3dheight",
	CudaDevAttrMaxTexture3dheightAlt:                  "CudaDevAttrMaxTexture3dheightAlt",
	CudaDevAttrMaxTexture3dwidth:                      "CudaDevAttrMaxTexture3dwidth",
	CudaDevAttrMaxTexture3dwidthAlt:                   "CudaDevAttrMaxTexture3dwidthAlt",
	CudaDevAttrMaxTextureCubemapLayeredLayers:         "CudaDevAttrMaxTextureCubemapLayeredLayers",
	CudaDevAttrMaxTextureCubemapLayeredWidth:          "CudaDevAttrMaxTextureCubemapLayeredWidth",
	CudaDevAttrMaxTextureCubemapWidth:                 "CudaDevAttrMaxTextureCubemapWidth",
	CudaDevAttrMaxThreadsPerBlock:                     "CudaDevAttrMaxThreadsPerBlock",
	CudaDevAttrMaxThreadsPerMultiProcessor:            "CudaDevAttrMaxThreadsPerMultiProcessor",
	CudaDevAttrMemSyncDomainCount:                     "CudaDevAttrMemSyncDomainCount",
	CudaDevAttrMemoryClockRate:                        "CudaDevAttrMemoryClockRate",
	CudaDevAttrMemoryPoolSupportedHandleTypes:         "CudaDevAttrMemoryPoolSupportedHandleTypes",
	CudaDevAttrMemoryPoolsSupported:                   "CudaDevAttrMemoryPoolsSupported",
	CudaDevAttrMpsEnabled:                             "CudaDevAttrMpsEnabled",
	CudaDevAttrMultiGpuBoardGroupId:                   "CudaDevAttrMultiGpuBoardGroupId",
	CudaDevAttrMultiProcessorCount:                    "CudaDevAttrMultiProcessorCount",
	CudaDevAttrNumaConfig:                             "CudaDevAttrNumaConfig",
	CudaDevAttrNumaId:                                 "CudaDevAttrNumaId",
	CudaDevAttrOnlyPartialHostNativeAtomicSupported:   "CudaDevAttrOnlyPartialHostNativeAtomicSupported",
	CudaDevAttrPageableMemoryAccess:                   "CudaDevAttrPageableMemoryAccess",
	CudaDevAttrPageableMemoryAccessUsesHostPageTables: "CudaDevAttrPageableMemoryAccessUsesHostPageTables",
	CudaDevAttrPciBusId:                               "CudaDevAttrPciBusId",
	CudaDevAttrPciDeviceId:                            "CudaDevAttrPciDeviceId",
	CudaDevAttrPciDomainId:                            "CudaDevAttrPciDomainId",
	CudaDevAttrReserved122:                            "CudaDevAttrReserved122",
	CudaDevAttrReserved123:                            "CudaDevAttrReserved123",
	CudaDevAttrReserved124:                            "CudaDevAttrReserved124",
	CudaDevAttrReserved127:                            "CudaDevAttrReserved127",
	CudaDevAttrReserved128:                            "CudaDevAttrReserved128",
	CudaDevAttrReserved129:                            "CudaDevAttrReserved129",
	CudaDevAttrReserved132:                            "CudaDevAttrReserved132",
	CudaDevAttrReserved141:                            "CudaDevAttrReserved141",
	CudaDevAttrReserved145:                            "CudaDevAttrReserved145",
	CudaDevAttrReserved92:                             "CudaDevAttrReserved92",
	CudaDevAttrReserved93:                             "CudaDevAttrReserved93",
	CudaDevAttrReserved94:                             "CudaDevAttrReserved94",
	CudaDevAttrReserved96:                             "CudaDevAttrReserved96",
	CudaDevAttrReservedSharedMemoryPerBlock:           "CudaDevAttrReservedSharedMemoryPerBlock",
	CudaDevAttrSingleToDoublePrecisionPerfRatio:       "CudaDevAttrSingleToDoublePrecisionPerfRatio",
	CudaDevAttrSparseCudaArraySupported:               "CudaDevAttrSparseCudaArraySupported",
	CudaDevAttrStreamPrioritiesSupported:              "CudaDevAttrStreamPrioritiesSupported",
	CudaDevAttrSurfaceAlignment:                       "CudaDevAttrSurfaceAlignment",
	CudaDevAttrTccDriver:                              "CudaDevAttrTccDriver",
	CudaDevAttrTextureAlignment:                       "CudaDevAttrTextureAlignment",
	CudaDevAttrTexturePitchAlignment:                  "CudaDevAttrTexturePitchAlignment",
	CudaDevAttrTimelineSemaphoreInteropSupported:      "CudaDevAttrTimelineSemaphoreInteropSupported",
	CudaDevAttrTotalConstantMemory:                    "CudaDevAttrTotalConstantMemory",
	CudaDevAttrUnifiedAddressing:                      "CudaDevAttrUnifiedAddressing",
	CudaDevAttrVulkanCigSupported:                     "CudaDevAttrVulkanCigSupported",
	CudaDevAttrWarpSize:                               "CudaDevAttrWarpSize",
}
