// Code generated by generator.go; DO NOT EDIT.
//go:build cuda13
// +build cuda13

package cudart

/*
#include <cuda_runtime.h>
*/
import "C"

// Constants for Error.
const (
	CudaErrorAddressOfConstant              Error = C.cudaErrorAddressOfConstant
	CudaErrorAlreadyAcquired                Error = C.cudaErrorAlreadyAcquired
	CudaErrorAlreadyMapped                  Error = C.cudaErrorAlreadyMapped
	CudaErrorArrayIsMapped                  Error = C.cudaErrorArrayIsMapped
	CudaErrorAssert                         Error = C.cudaErrorAssert
	CudaErrorCallRequiresNewerDriver        Error = C.cudaErrorCallRequiresNewerDriver
	CudaErrorCapturedEvent                  Error = C.cudaErrorCapturedEvent
	CudaErrorCdpNotSupported                Error = C.cudaErrorCdpNotSupported
	CudaErrorCdpVersionMismatch             Error = C.cudaErrorCdpVersionMismatch
	CudaErrorCompatNotSupportedOnDevice     Error = C.cudaErrorCompatNotSupportedOnDevice
	CudaErrorContained                      Error = C.cudaErrorContained
	CudaErrorContextIsDestroyed             Error = C.cudaErrorContextIsDestroyed
	CudaErrorCooperativeLaunchTooLarge      Error = C.cudaErrorCooperativeLaunchTooLarge
	CudaErrorCudartUnloading                Error = C.cudaErrorCudartUnloading
	CudaErrorDeviceAlreadyInUse             Error = C.cudaErrorDeviceAlreadyInUse
	CudaErrorDeviceNotLicensed              Error = C.cudaErrorDeviceNotLicensed
	CudaErrorDeviceUninitialized            Error = C.cudaErrorDeviceUninitialized
	CudaErrorDevicesUnavailable             Error = C.cudaErrorDevicesUnavailable
	CudaErrorDuplicateSurfaceName           Error = C.cudaErrorDuplicateSurfaceName
	CudaErrorDuplicateTextureName           Error = C.cudaErrorDuplicateTextureName
	CudaErrorDuplicateVariableName          Error = C.cudaErrorDuplicateVariableName
	CudaErrorEccuncorrectable               Error = C.cudaErrorECCUncorrectable
	CudaErrorExternalDevice                 Error = C.cudaErrorExternalDevice
	CudaErrorFileNotFound                   Error = C.cudaErrorFileNotFound
	CudaErrorFunctionNotLoaded              Error = C.cudaErrorFunctionNotLoaded
	CudaErrorGraphExecUpdateFailure         Error = C.cudaErrorGraphExecUpdateFailure
	CudaErrorHardwareStackError             Error = C.cudaErrorHardwareStackError
	CudaErrorHostMemoryAlreadyRegistered    Error = C.cudaErrorHostMemoryAlreadyRegistered
	CudaErrorHostMemoryNotRegistered        Error = C.cudaErrorHostMemoryNotRegistered
	CudaErrorIllegalAddress                 Error = C.cudaErrorIllegalAddress
	CudaErrorIllegalInstruction             Error = C.cudaErrorIllegalInstruction
	CudaErrorIllegalState                   Error = C.cudaErrorIllegalState
	CudaErrorIncompatibleDriverContext      Error = C.cudaErrorIncompatibleDriverContext
	CudaErrorInitializationError            Error = C.cudaErrorInitializationError
	CudaErrorInsufficientDriver             Error = C.cudaErrorInsufficientDriver
	CudaErrorInvalidAddressSpace            Error = C.cudaErrorInvalidAddressSpace
	CudaErrorInvalidChannelDescriptor       Error = C.cudaErrorInvalidChannelDescriptor
	CudaErrorInvalidClusterSize             Error = C.cudaErrorInvalidClusterSize
	CudaErrorInvalidConfiguration           Error = C.cudaErrorInvalidConfiguration
	CudaErrorInvalidDevice                  Error = C.cudaErrorInvalidDevice
	CudaErrorInvalidDeviceFunction          Error = C.cudaErrorInvalidDeviceFunction
	CudaErrorInvalidDevicePointer           Error = C.cudaErrorInvalidDevicePointer
	CudaErrorInvalidFilterSetting           Error = C.cudaErrorInvalidFilterSetting
	CudaErrorInvalidGraphicsContext         Error = C.cudaErrorInvalidGraphicsContext
	CudaErrorInvalidHostPointer             Error = C.cudaErrorInvalidHostPointer
	CudaErrorInvalidKernelImage             Error = C.cudaErrorInvalidKernelImage
	CudaErrorInvalidMemcpyDirection         Error = C.cudaErrorInvalidMemcpyDirection
	CudaErrorInvalidNormSetting             Error = C.cudaErrorInvalidNormSetting
	CudaErrorInvalidPc                      Error = C.cudaErrorInvalidPc
	CudaErrorInvalidPitchValue              Error = C.cudaErrorInvalidPitchValue
	CudaErrorInvalidPtx                     Error = C.cudaErrorInvalidPtx
	CudaErrorInvalidResourceConfiguration   Error = C.cudaErrorInvalidResourceConfiguration
	CudaErrorInvalidResourceHandle          Error = C.cudaErrorInvalidResourceHandle
	CudaErrorInvalidResourceType            Error = C.cudaErrorInvalidResourceType
	CudaErrorInvalidSource                  Error = C.cudaErrorInvalidSource
	CudaErrorInvalidSurface                 Error = C.cudaErrorInvalidSurface
	CudaErrorInvalidSymbol                  Error = C.cudaErrorInvalidSymbol
	CudaErrorInvalidTexture                 Error = C.cudaErrorInvalidTexture
	CudaErrorInvalidTextureBinding          Error = C.cudaErrorInvalidTextureBinding
	CudaErrorInvalidValue                   Error = C.cudaErrorInvalidValue
	CudaErrorJitCompilationDisabled         Error = C.cudaErrorJitCompilationDisabled
	CudaErrorJitCompilerNotFound            Error = C.cudaErrorJitCompilerNotFound
	CudaErrorLaunchFailure                  Error = C.cudaErrorLaunchFailure
	CudaErrorLaunchFileScopedSurf           Error = C.cudaErrorLaunchFileScopedSurf
	CudaErrorLaunchFileScopedTex            Error = C.cudaErrorLaunchFileScopedTex
	CudaErrorLaunchIncompatibleTexturing    Error = C.cudaErrorLaunchIncompatibleTexturing
	CudaErrorLaunchMaxDepthExceeded         Error = C.cudaErrorLaunchMaxDepthExceeded
	CudaErrorLaunchOutOfResources           Error = C.cudaErrorLaunchOutOfResources
	CudaErrorLaunchPendingCountExceeded     Error = C.cudaErrorLaunchPendingCountExceeded
	CudaErrorLaunchTimeout                  Error = C.cudaErrorLaunchTimeout
	CudaErrorLossyQuery                     Error = C.cudaErrorLossyQuery
	CudaErrorMapBufferObjectFailed          Error = C.cudaErrorMapBufferObjectFailed
	CudaErrorMemoryAllocation               Error = C.cudaErrorMemoryAllocation
	CudaErrorMemoryValueTooLarge            Error = C.cudaErrorMemoryValueTooLarge
	CudaErrorMisalignedAddress              Error = C.cudaErrorMisalignedAddress
	CudaErrorMissingConfiguration           Error = C.cudaErrorMissingConfiguration
	CudaErrorMixedDeviceExecution           Error = C.cudaErrorMixedDeviceExecution
	CudaErrorMpsClientTerminated            Error = C.cudaErrorMpsClientTerminated
	CudaErrorMpsConnectionFailed            Error = C.cudaErrorMpsConnectionFailed
	CudaErrorMpsMaxClientsReached           Error = C.cudaErrorMpsMaxClientsReached
	CudaErrorMpsMaxConnectionsReached       Error = C.cudaErrorMpsMaxConnectionsReached
	CudaErrorMpsRpcFailure                  Error = C.cudaErrorMpsRpcFailure
	CudaErrorMpsServerNotReady              Error = C.cudaErrorMpsServerNotReady
	CudaErrorNoDevice                       Error = C.cudaErrorNoDevice
	CudaErrorNoKernelImageForDevice         Error = C.cudaErrorNoKernelImageForDevice
	CudaErrorNotMapped                      Error = C.cudaErrorNotMapped
	CudaErrorNotMappedAsArray               Error = C.cudaErrorNotMappedAsArray
	CudaErrorNotMappedAsPointer             Error = C.cudaErrorNotMappedAsPointer
	CudaErrorNotPermitted                   Error = C.cudaErrorNotPermitted
	CudaErrorNotReady                       Error = C.cudaErrorNotReady
	CudaErrorNotSupported                   Error = C.cudaErrorNotSupported
	CudaErrorNotYetImplemented              Error = C.cudaErrorNotYetImplemented
	CudaErrorNvlinkUncorrectable            Error = C.cudaErrorNvlinkUncorrectable
	CudaErrorOperatingSystem                Error = C.cudaErrorOperatingSystem
	CudaErrorPeerAccessAlreadyEnabled       Error = C.cudaErrorPeerAccessAlreadyEnabled
	CudaErrorPeerAccessNotEnabled           Error = C.cudaErrorPeerAccessNotEnabled
	CudaErrorPeerAccessUnsupported          Error = C.cudaErrorPeerAccessUnsupported
	CudaErrorPriorLaunchFailure             Error = C.cudaErrorPriorLaunchFailure
	CudaErrorProfilerAlreadyStarted         Error = C.cudaErrorProfilerAlreadyStarted
	CudaErrorProfilerAlreadyStopped         Error = C.cudaErrorProfilerAlreadyStopped
	CudaErrorProfilerDisabled               Error = C.cudaErrorProfilerDisabled
	CudaErrorProfilerNotInitialized         Error = C.cudaErrorProfilerNotInitialized
	CudaErrorSetOnActiveProcess             Error = C.cudaErrorSetOnActiveProcess
	CudaErrorSharedObjectInitFailed         Error = C.cudaErrorSharedObjectInitFailed
	CudaErrorSharedObjectSymbolNotFound     Error = C.cudaErrorSharedObjectSymbolNotFound
	CudaErrorSoftwareValidityNotEstablished Error = C.cudaErrorSoftwareValidityNotEstablished
	CudaErrorStartupFailure                 Error = C.cudaErrorStartupFailure
	CudaErrorStreamCaptureImplicit          Error = C.cudaErrorStreamCaptureImplicit
	CudaErrorStreamCaptureInvalidated       Error = C.cudaErrorStreamCaptureInvalidated
	CudaErrorStreamCaptureIsolation         Error = C.cudaErrorStreamCaptureIsolation
	CudaErrorStreamCaptureMerge             Error = C.cudaErrorStreamCaptureMerge
	CudaErrorStreamCaptureUnjoined          Error = C.cudaErrorStreamCaptureUnjoined
	CudaErrorStreamCaptureUnmatched         Error = C.cudaErrorStreamCaptureUnmatched
	CudaErrorStreamCaptureUnsupported       Error = C.cudaErrorStreamCaptureUnsupported
	CudaErrorStreamCaptureWrongThread       Error = C.cudaErrorStreamCaptureWrongThread
	CudaErrorStubLibrary                    Error = C.cudaErrorStubLibrary
	CudaErrorSymbolNotFound                 Error = C.cudaErrorSymbolNotFound
	CudaErrorSyncDepthExceeded              Error = C.cudaErrorSyncDepthExceeded
	CudaErrorSynchronizationError           Error = C.cudaErrorSynchronizationError
	CudaErrorSystemDriverMismatch           Error = C.cudaErrorSystemDriverMismatch
	CudaErrorSystemNotReady                 Error = C.cudaErrorSystemNotReady
	CudaErrorTensorMemoryLeak               Error = C.cudaErrorTensorMemoryLeak
	CudaErrorTextureFetchFailed             Error = C.cudaErrorTextureFetchFailed
	CudaErrorTextureNotBound                Error = C.cudaErrorTextureNotBound
	CudaErrorTimeout                        Error = C.cudaErrorTimeout
	CudaErrorTooManyPeers                   Error = C.cudaErrorTooManyPeers
	CudaErrorUnknown                        Error = C.cudaErrorUnknown
	CudaErrorUnmapBufferObjectFailed        Error = C.cudaErrorUnmapBufferObjectFailed
	CudaErrorUnsupportedDevSideSync         Error = C.cudaErrorUnsupportedDevSideSync
	CudaErrorUnsupportedExecAffinity        Error = C.cudaErrorUnsupportedExecAffinity
	CudaErrorUnsupportedLimit               Error = C.cudaErrorUnsupportedLimit
	CudaErrorUnsupportedPtxVersion          Error = C.cudaErrorUnsupportedPtxVersion
	CudaSuccess                             Error = C.cudaSuccess
)

// ErrorMessages maps Error values to their string representations.
var ErrorMessages = map[Error]string{
	CudaErrorAddressOfConstant:              "CudaErrorAddressOfConstant",
	CudaErrorAlreadyAcquired:                "CudaErrorAlreadyAcquired",
	CudaErrorAlreadyMapped:                  "CudaErrorAlreadyMapped",
	CudaErrorArrayIsMapped:                  "CudaErrorArrayIsMapped",
	CudaErrorAssert:                         "CudaErrorAssert",
	CudaErrorCallRequiresNewerDriver:        "CudaErrorCallRequiresNewerDriver",
	CudaErrorCapturedEvent:                  "CudaErrorCapturedEvent",
	CudaErrorCdpNotSupported:                "CudaErrorCdpNotSupported",
	CudaErrorCdpVersionMismatch:             "CudaErrorCdpVersionMismatch",
	CudaErrorCompatNotSupportedOnDevice:     "CudaErrorCompatNotSupportedOnDevice",
	CudaErrorContained:                      "CudaErrorContained",
	CudaErrorContextIsDestroyed:             "CudaErrorContextIsDestroyed",
	CudaErrorCooperativeLaunchTooLarge:      "CudaErrorCooperativeLaunchTooLarge",
	CudaErrorCudartUnloading:                "CudaErrorCudartUnloading",
	CudaErrorDeviceAlreadyInUse:             "CudaErrorDeviceAlreadyInUse",
	CudaErrorDeviceNotLicensed:              "CudaErrorDeviceNotLicensed",
	CudaErrorDeviceUninitialized:            "CudaErrorDeviceUninitialized",
	CudaErrorDevicesUnavailable:             "CudaErrorDevicesUnavailable",
	CudaErrorDuplicateSurfaceName:           "CudaErrorDuplicateSurfaceName",
	CudaErrorDuplicateTextureName:           "CudaErrorDuplicateTextureName",
	CudaErrorDuplicateVariableName:          "CudaErrorDuplicateVariableName",
	CudaErrorEccuncorrectable:               "CudaErrorEccuncorrectable",
	CudaErrorExternalDevice:                 "CudaErrorExternalDevice",
	CudaErrorFileNotFound:                   "CudaErrorFileNotFound",
	CudaErrorFunctionNotLoaded:              "CudaErrorFunctionNotLoaded",
	CudaErrorGraphExecUpdateFailure:         "CudaErrorGraphExecUpdateFailure",
	CudaErrorHardwareStackError:             "CudaErrorHardwareStackError",
	CudaErrorHostMemoryAlreadyRegistered:    "CudaErrorHostMemoryAlreadyRegistered",
	CudaErrorHostMemoryNotRegistered:        "CudaErrorHostMemoryNotRegistered",
	CudaErrorIllegalAddress:                 "CudaErrorIllegalAddress",
	CudaErrorIllegalInstruction:             "CudaErrorIllegalInstruction",
	CudaErrorIllegalState:                   "CudaErrorIllegalState",
	CudaErrorIncompatibleDriverContext:      "CudaErrorIncompatibleDriverContext",
	CudaErrorInitializationError:            "CudaErrorInitializationError",
	CudaErrorInsufficientDriver:             "CudaErrorInsufficientDriver",
	CudaErrorInvalidAddressSpace:            "CudaErrorInvalidAddressSpace",
	CudaErrorInvalidChannelDescriptor:       "CudaErrorInvalidChannelDescriptor",
	CudaErrorInvalidClusterSize:             "CudaErrorInvalidClusterSize",
	CudaErrorInvalidConfiguration:           "CudaErrorInvalidConfiguration",
	CudaErrorInvalidDevice:                  "CudaErrorInvalidDevice",
	CudaErrorInvalidDeviceFunction:          "CudaErrorInvalidDeviceFunction",
	CudaErrorInvalidDevicePointer:           "CudaErrorInvalidDevicePointer",
	CudaErrorInvalidFilterSetting:           "CudaErrorInvalidFilterSetting",
	CudaErrorInvalidGraphicsContext:         "CudaErrorInvalidGraphicsContext",
	CudaErrorInvalidHostPointer:             "CudaErrorInvalidHostPointer",
	CudaErrorInvalidKernelImage:             "CudaErrorInvalidKernelImage",
	CudaErrorInvalidMemcpyDirection:         "CudaErrorInvalidMemcpyDirection",
	CudaErrorInvalidNormSetting:             "CudaErrorInvalidNormSetting",
	CudaErrorInvalidPc:                      "CudaErrorInvalidPc",
	CudaErrorInvalidPitchValue:              "CudaErrorInvalidPitchValue",
	CudaErrorInvalidPtx:                     "CudaErrorInvalidPtx",
	CudaErrorInvalidResourceConfiguration:   "CudaErrorInvalidResourceConfiguration",
	CudaErrorInvalidResourceHandle:          "CudaErrorInvalidResourceHandle",
	CudaErrorInvalidResourceType:            "CudaErrorInvalidResourceType",
	CudaErrorInvalidSource:                  "CudaErrorInvalidSource",
	CudaErrorInvalidSurface:                 "CudaErrorInvalidSurface",
	CudaErrorInvalidSymbol:                  "CudaErrorInvalidSymbol",
	CudaErrorInvalidTexture:                 "CudaErrorInvalidTexture",
	CudaErrorInvalidTextureBinding:          "CudaErrorInvalidTextureBinding",
	CudaErrorInvalidValue:                   "CudaErrorInvalidValue",
	CudaErrorJitCompilationDisabled:         "CudaErrorJitCompilationDisabled",
	CudaErrorJitCompilerNotFound:            "CudaErrorJitCompilerNotFound",
	CudaErrorLaunchFailure:                  "CudaErrorLaunchFailure",
	CudaErrorLaunchFileScopedSurf:           "CudaErrorLaunchFileScopedSurf",
	CudaErrorLaunchFileScopedTex:            "CudaErrorLaunchFileScopedTex",
	CudaErrorLaunchIncompatibleTexturing:    "CudaErrorLaunchIncompatibleTexturing",
	CudaErrorLaunchMaxDepthExceeded:         "CudaErrorLaunchMaxDepthExceeded",
	CudaErrorLaunchOutOfResources:           "CudaErrorLaunchOutOfResources",
	CudaErrorLaunchPendingCountExceeded:     "CudaErrorLaunchPendingCountExceeded",
	CudaErrorLaunchTimeout:                  "CudaErrorLaunchTimeout",
	CudaErrorLossyQuery:                     "CudaErrorLossyQuery",
	CudaErrorMapBufferObjectFailed:          "CudaErrorMapBufferObjectFailed",
	CudaErrorMemoryAllocation:               "CudaErrorMemoryAllocation",
	CudaErrorMemoryValueTooLarge:            "CudaErrorMemoryValueTooLarge",
	CudaErrorMisalignedAddress:              "CudaErrorMisalignedAddress",
	CudaErrorMissingConfiguration:           "CudaErrorMissingConfiguration",
	CudaErrorMixedDeviceExecution:           "CudaErrorMixedDeviceExecution",
	CudaErrorMpsClientTerminated:            "CudaErrorMpsClientTerminated",
	CudaErrorMpsConnectionFailed:            "CudaErrorMpsConnectionFailed",
	CudaErrorMpsMaxClientsReached:           "CudaErrorMpsMaxClientsReached",
	CudaErrorMpsMaxConnectionsReached:       "CudaErrorMpsMaxConnectionsReached",
	CudaErrorMpsRpcFailure:                  "CudaErrorMpsRpcFailure",
	CudaErrorMpsServerNotReady:              "CudaErrorMpsServerNotReady",
	CudaErrorNoDevice:                       "CudaErrorNoDevice",
	CudaErrorNoKernelImageForDevice:         "CudaErrorNoKernelImageForDevice",
	CudaErrorNotMapped:                      "CudaErrorNotMapped",
	CudaErrorNotMappedAsArray:               "CudaErrorNotMappedAsArray",
	CudaErrorNotMappedAsPointer:             "CudaErrorNotMappedAsPointer",
	CudaErrorNotPermitted:                   "CudaErrorNotPermitted",
	CudaErrorNotReady:                       "CudaErrorNotReady",
	CudaErrorNotSupported:                   "CudaErrorNotSupported",
	CudaErrorNotYetImplemented:              "CudaErrorNotYetImplemented",
	CudaErrorNvlinkUncorrectable:            "CudaErrorNvlinkUncorrectable",
	CudaErrorOperatingSystem:                "CudaErrorOperatingSystem",
	CudaErrorPeerAccessAlreadyEnabled:       "CudaErrorPeerAccessAlreadyEnabled",
	CudaErrorPeerAccessNotEnabled:           "CudaErrorPeerAccessNotEnabled",
	CudaErrorPeerAccessUnsupported:          "CudaErrorPeerAccessUnsupported",
	CudaErrorPriorLaunchFailure:             "CudaErrorPriorLaunchFailure",
	CudaErrorProfilerAlreadyStarted:         "CudaErrorProfilerAlreadyStarted",
	CudaErrorProfilerAlreadyStopped:         "CudaErrorProfilerAlreadyStopped",
	CudaErrorProfilerDisabled:               "CudaErrorProfilerDisabled",
	CudaErrorProfilerNotInitialized:         "CudaErrorProfilerNotInitialized",
	CudaErrorSetOnActiveProcess:             "CudaErrorSetOnActiveProcess",
	CudaErrorSharedObjectInitFailed:         "CudaErrorSharedObjectInitFailed",
	CudaErrorSharedObjectSymbolNotFound:     "CudaErrorSharedObjectSymbolNotFound",
	CudaErrorSoftwareValidityNotEstablished: "CudaErrorSoftwareValidityNotEstablished",
	CudaErrorStartupFailure:                 "CudaErrorStartupFailure",
	CudaErrorStreamCaptureImplicit:          "CudaErrorStreamCaptureImplicit",
	CudaErrorStreamCaptureInvalidated:       "CudaErrorStreamCaptureInvalidated",
	CudaErrorStreamCaptureIsolation:         "CudaErrorStreamCaptureIsolation",
	CudaErrorStreamCaptureMerge:             "CudaErrorStreamCaptureMerge",
	CudaErrorStreamCaptureUnjoined:          "CudaErrorStreamCaptureUnjoined",
	CudaErrorStreamCaptureUnmatched:         "CudaErrorStreamCaptureUnmatched",
	CudaErrorStreamCaptureUnsupported:       "CudaErrorStreamCaptureUnsupported",
	CudaErrorStreamCaptureWrongThread:       "CudaErrorStreamCaptureWrongThread",
	CudaErrorStubLibrary:                    "CudaErrorStubLibrary",
	CudaErrorSymbolNotFound:                 "CudaErrorSymbolNotFound",
	CudaErrorSyncDepthExceeded:              "CudaErrorSyncDepthExceeded",
	CudaErrorSynchronizationError:           "CudaErrorSynchronizationError",
	CudaErrorSystemDriverMismatch:           "CudaErrorSystemDriverMismatch",
	CudaErrorSystemNotReady:                 "CudaErrorSystemNotReady",
	CudaErrorTensorMemoryLeak:               "CudaErrorTensorMemoryLeak",
	CudaErrorTextureFetchFailed:             "CudaErrorTextureFetchFailed",
	CudaErrorTextureNotBound:                "CudaErrorTextureNotBound",
	CudaErrorTimeout:                        "CudaErrorTimeout",
	CudaErrorTooManyPeers:                   "CudaErrorTooManyPeers",
	CudaErrorUnknown:                        "CudaErrorUnknown",
	CudaErrorUnmapBufferObjectFailed:        "CudaErrorUnmapBufferObjectFailed",
	CudaErrorUnsupportedDevSideSync:         "CudaErrorUnsupportedDevSideSync",
	CudaErrorUnsupportedExecAffinity:        "CudaErrorUnsupportedExecAffinity",
	CudaErrorUnsupportedLimit:               "CudaErrorUnsupportedLimit",
	CudaErrorUnsupportedPtxVersion:          "CudaErrorUnsupportedPtxVersion",
	CudaSuccess:                             "CudaSuccess",
}
